/*
 * Kibo SubscriptionRuntime Service
 * OpenAPI Spec for Kibo SubscriptionRuntime Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.subscription.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.subscription.models.CommerceRuntimeDiscount;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CommerceRuntimeAppliedLineItemProductDiscount
 */
public class CommerceRuntimeAppliedLineItemProductDiscountTest {
    private final CommerceRuntimeAppliedLineItemProductDiscount model = new CommerceRuntimeAppliedLineItemProductDiscount();

    /**
     * Model tests for CommerceRuntimeAppliedLineItemProductDiscount
     */
    @Test
    public void testCommerceRuntimeAppliedLineItemProductDiscount() {
        // TODO: test CommerceRuntimeAppliedLineItemProductDiscount
    }

    /**
     * Test the property 'impact'
     */
    @Test
    public void impactTest() {
        // TODO: test impact
    }

    /**
     * Test the property 'discount'
     */
    @Test
    public void discountTest() {
        // TODO: test discount
    }

    /**
     * Test the property 'couponCode'
     */
    @Test
    public void couponCodeTest() {
        // TODO: test couponCode
    }

    /**
     * Test the property 'excluded'
     */
    @Test
    public void excludedTest() {
        // TODO: test excluded
    }

}
