/*
 * Kibo SubscriptionRuntime Service
 * OpenAPI Spec for Kibo SubscriptionRuntime Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.subscription.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.subscription.models.CommerceRuntimePurchaseOrderCustomField;
import com.kibocommerce.sdk.subscription.models.CommerceRuntimePurchaseOrderPaymentTerm;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PurchaseOrderPayment
 */
public class PurchaseOrderPaymentTest {
    private final PurchaseOrderPayment model = new PurchaseOrderPayment();

    /**
     * Model tests for PurchaseOrderPayment
     */
    @Test
    public void testPurchaseOrderPayment() {
        // TODO: test PurchaseOrderPayment
    }

    /**
     * Test the property 'purchaseOrderNumber'
     */
    @Test
    public void purchaseOrderNumberTest() {
        // TODO: test purchaseOrderNumber
    }

    /**
     * Test the property 'paymentTerm'
     */
    @Test
    public void paymentTermTest() {
        // TODO: test paymentTerm
    }

    /**
     * Test the property 'customFields'
     */
    @Test
    public void customFieldsTest() {
        // TODO: test customFields
    }

}
