/*
 * Kibo SubscriptionRuntime Service
 * OpenAPI Spec for Kibo SubscriptionRuntime Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.subscription.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.subscription.models.SubscriptionReason;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SubscriptionAdjustment
 */
public class SubscriptionAdjustmentTest {
    private final SubscriptionAdjustment model = new SubscriptionAdjustment();

    /**
     * Model tests for SubscriptionAdjustment
     */
    @Test
    public void testSubscriptionAdjustment() {
        // TODO: test SubscriptionAdjustment
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'itemAdjustment'
     */
    @Test
    public void itemAdjustmentTest() {
        // TODO: test itemAdjustment
    }

    /**
     * Test the property 'shippingAdjustment'
     */
    @Test
    public void shippingAdjustmentTest() {
        // TODO: test shippingAdjustment
    }

    /**
     * Test the property 'handlingAdjustment'
     */
    @Test
    public void handlingAdjustmentTest() {
        // TODO: test handlingAdjustment
    }

}
