/*
 * Kibo SubscriptionRuntime Service
 * OpenAPI Spec for Kibo SubscriptionRuntime Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.subscription.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.subscription.models.Adjustment;
import com.kibocommerce.sdk.subscription.models.AdminUserAuditInfo;
import com.kibocommerce.sdk.subscription.models.CommerceRuntimeAppliedDiscount;
import com.kibocommerce.sdk.subscription.models.CommerceRuntimeChangeMessage;
import com.kibocommerce.sdk.subscription.models.Frequency;
import com.kibocommerce.sdk.subscription.models.FulfillmentInfo;
import com.kibocommerce.sdk.subscription.models.InvalidCoupon;
import com.kibocommerce.sdk.subscription.models.OnetimeProduct;
import com.kibocommerce.sdk.subscription.models.OnetimeShippingMethod;
import com.kibocommerce.sdk.subscription.models.OrderNote;
import com.kibocommerce.sdk.subscription.models.Payment;
import com.kibocommerce.sdk.subscription.models.ShippingDiscount;
import com.kibocommerce.sdk.subscription.models.SubscriptionItem;
import com.kibocommerce.sdk.subscription.models.SubscriptionReason;
import com.kibocommerce.sdk.subscription.models.Trial;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SubscriptionRuntimeSubscription
 */
public class SubscriptionRuntimeSubscriptionTest {
    private final SubscriptionRuntimeSubscription model = new SubscriptionRuntimeSubscription();

    /**
     * Model tests for SubscriptionRuntimeSubscription
     */
    @Test
    public void testSubscriptionRuntimeSubscription() {
        // TODO: test SubscriptionRuntimeSubscription
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'siteId'
     */
    @Test
    public void siteIdTest() {
        // TODO: test siteId
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'number'
     */
    @Test
    public void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'parentOrderId'
     */
    @Test
    public void parentOrderIdTest() {
        // TODO: test parentOrderId
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'payment'
     */
    @Test
    public void paymentTest() {
        // TODO: test payment
    }

    /**
     * Test the property 'priceListCode'
     */
    @Test
    public void priceListCodeTest() {
        // TODO: test priceListCode
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'oneTimeCouponCodes'
     */
    @Test
    public void oneTimeCouponCodesTest() {
        // TODO: test oneTimeCouponCodes
    }

    /**
     * Test the property 'changeMessages'
     */
    @Test
    public void changeMessagesTest() {
        // TODO: test changeMessages
    }

    /**
     * Test the property 'auditInfo'
     */
    @Test
    public void auditInfoTest() {
        // TODO: test auditInfo
    }

    /**
     * Test the property 'fulfillmentInfo'
     */
    @Test
    public void fulfillmentInfoTest() {
        // TODO: test fulfillmentInfo
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'customerAccountId'
     */
    @Test
    public void customerAccountIdTest() {
        // TODO: test customerAccountId
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'customerTaxId'
     */
    @Test
    public void customerTaxIdTest() {
        // TODO: test customerTaxId
    }

    /**
     * Test the property 'isTaxExempt'
     */
    @Test
    public void isTaxExemptTest() {
        // TODO: test isTaxExempt
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'taxData'
     */
    @Test
    public void taxDataTest() {
        // TODO: test taxData
    }

    /**
     * Test the property 'channelCode'
     */
    @Test
    public void channelCodeTest() {
        // TODO: test channelCode
    }

    /**
     * Test the property 'locationCode'
     */
    @Test
    public void locationCodeTest() {
        // TODO: test locationCode
    }

    /**
     * Test the property 'ipAddress'
     */
    @Test
    public void ipAddressTest() {
        // TODO: test ipAddress
    }

    /**
     * Test the property 'sourceDevice'
     */
    @Test
    public void sourceDeviceTest() {
        // TODO: test sourceDevice
    }

    /**
     * Test the property 'visitId'
     */
    @Test
    public void visitIdTest() {
        // TODO: test visitId
    }

    /**
     * Test the property 'webSessionId'
     */
    @Test
    public void webSessionIdTest() {
        // TODO: test webSessionId
    }

    /**
     * Test the property 'customerInteractionType'
     */
    @Test
    public void customerInteractionTypeTest() {
        // TODO: test customerInteractionType
    }

    /**
     * Test the property 'frequency'
     */
    @Test
    public void frequencyTest() {
        // TODO: test frequency
    }

    /**
     * Test the property 'previousFrequency'
     */
    @Test
    public void previousFrequencyTest() {
        // TODO: test previousFrequency
    }

    /**
     * Test the property 'frequencyAuditInfo'
     */
    @Test
    public void frequencyAuditInfoTest() {
        // TODO: test frequencyAuditInfo
    }

    /**
     * Test the property 'nextOrderDate'
     */
    @Test
    public void nextOrderDateTest() {
        // TODO: test nextOrderDate
    }

    /**
     * Test the property 'previousNextOrderDate'
     */
    @Test
    public void previousNextOrderDateTest() {
        // TODO: test previousNextOrderDate
    }

    /**
     * Test the property 'nextOrderDateAuditInfo'
     */
    @Test
    public void nextOrderDateAuditInfoTest() {
        // TODO: test nextOrderDateAuditInfo
    }

    /**
     * Test the property 'lastContinuityOrderDateOnSubPaused'
     */
    @Test
    public void lastContinuityOrderDateOnSubPausedTest() {
        // TODO: test lastContinuityOrderDateOnSubPaused
    }

    /**
     * Test the property 'ordinal'
     */
    @Test
    public void ordinalTest() {
        // TODO: test ordinal
    }

    /**
     * Test the property 'paymentErrorCode'
     */
    @Test
    public void paymentErrorCodeTest() {
        // TODO: test paymentErrorCode
    }

    /**
     * Test the property 'trial'
     */
    @Test
    public void trialTest() {
        // TODO: test trial
    }

    /**
     * Test the property 'orderDiscounts'
     */
    @Test
    public void orderDiscountsTest() {
        // TODO: test orderDiscounts
    }

    /**
     * Test the property 'subTotal'
     */
    @Test
    public void subTotalTest() {
        // TODO: test subTotal
    }

    /**
     * Test the property 'itemLevelProductDiscountTotal'
     */
    @Test
    public void itemLevelProductDiscountTotalTest() {
        // TODO: test itemLevelProductDiscountTotal
    }

    /**
     * Test the property 'itemLevelAdjustmentsTotal'
     */
    @Test
    public void itemLevelAdjustmentsTotalTest() {
        // TODO: test itemLevelAdjustmentsTotal
    }

    /**
     * Test the property 'orderLevelProductDiscountTotal'
     */
    @Test
    public void orderLevelProductDiscountTotalTest() {
        // TODO: test orderLevelProductDiscountTotal
    }

    /**
     * Test the property 'itemTaxTotal'
     */
    @Test
    public void itemTaxTotalTest() {
        // TODO: test itemTaxTotal
    }

    /**
     * Test the property 'adjustment'
     */
    @Test
    public void adjustmentTest() {
        // TODO: test adjustment
    }

    /**
     * Test the property 'itemTotal'
     */
    @Test
    public void itemTotalTest() {
        // TODO: test itemTotal
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

    /**
     * Test the property 'shippingDiscounts'
     */
    @Test
    public void shippingDiscountsTest() {
        // TODO: test shippingDiscounts
    }

    /**
     * Test the property 'itemLevelShippingDiscountTotal'
     */
    @Test
    public void itemLevelShippingDiscountTotalTest() {
        // TODO: test itemLevelShippingDiscountTotal
    }

    /**
     * Test the property 'orderLevelShippingDiscountTotal'
     */
    @Test
    public void orderLevelShippingDiscountTotalTest() {
        // TODO: test orderLevelShippingDiscountTotal
    }

    /**
     * Test the property 'shippingAmount'
     */
    @Test
    public void shippingAmountTest() {
        // TODO: test shippingAmount
    }

    /**
     * Test the property 'shippingAdjustment'
     */
    @Test
    public void shippingAdjustmentTest() {
        // TODO: test shippingAdjustment
    }

    /**
     * Test the property 'shippingSubTotal'
     */
    @Test
    public void shippingSubTotalTest() {
        // TODO: test shippingSubTotal
    }

    /**
     * Test the property 'shippingTax'
     */
    @Test
    public void shippingTaxTest() {
        // TODO: test shippingTax
    }

    /**
     * Test the property 'shippingTaxTotal'
     */
    @Test
    public void shippingTaxTotalTest() {
        // TODO: test shippingTaxTotal
    }

    /**
     * Test the property 'shippingTotal'
     */
    @Test
    public void shippingTotalTest() {
        // TODO: test shippingTotal
    }

    /**
     * Test the property 'handlingDiscounts'
     */
    @Test
    public void handlingDiscountsTest() {
        // TODO: test handlingDiscounts
    }

    /**
     * Test the property 'itemLevelHandlingDiscountTotal'
     */
    @Test
    public void itemLevelHandlingDiscountTotalTest() {
        // TODO: test itemLevelHandlingDiscountTotal
    }

    /**
     * Test the property 'orderLevelHandlingDiscountTotal'
     */
    @Test
    public void orderLevelHandlingDiscountTotalTest() {
        // TODO: test orderLevelHandlingDiscountTotal
    }

    /**
     * Test the property 'handlingAmount'
     */
    @Test
    public void handlingAmountTest() {
        // TODO: test handlingAmount
    }

    /**
     * Test the property 'handlingAdjustment'
     */
    @Test
    public void handlingAdjustmentTest() {
        // TODO: test handlingAdjustment
    }

    /**
     * Test the property 'handlingSubTotal'
     */
    @Test
    public void handlingSubTotalTest() {
        // TODO: test handlingSubTotal
    }

    /**
     * Test the property 'handlingTax'
     */
    @Test
    public void handlingTaxTest() {
        // TODO: test handlingTax
    }

    /**
     * Test the property 'handlingTaxTotal'
     */
    @Test
    public void handlingTaxTotalTest() {
        // TODO: test handlingTaxTotal
    }

    /**
     * Test the property 'handlingTotal'
     */
    @Test
    public void handlingTotalTest() {
        // TODO: test handlingTotal
    }

    /**
     * Test the property 'dutyAmount'
     */
    @Test
    public void dutyAmountTest() {
        // TODO: test dutyAmount
    }

    /**
     * Test the property 'dutyTotal'
     */
    @Test
    public void dutyTotalTest() {
        // TODO: test dutyTotal
    }

    /**
     * Test the property 'feeTotal'
     */
    @Test
    public void feeTotalTest() {
        // TODO: test feeTotal
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'reasons'
     */
    @Test
    public void reasonsTest() {
        // TODO: test reasons
    }

    /**
     * Test the property 'couponCodes'
     */
    @Test
    public void couponCodesTest() {
        // TODO: test couponCodes
    }

    /**
     * Test the property 'invalidCoupons'
     */
    @Test
    public void invalidCouponsTest() {
        // TODO: test invalidCoupons
    }

    /**
     * Test the property 'isImport'
     */
    @Test
    public void isImportTest() {
        // TODO: test isImport
    }

    /**
     * Test the property 'externalId'
     */
    @Test
    public void externalIdTest() {
        // TODO: test externalId
    }

    /**
     * Test the property 'lineItemSubtotalWithOrderAdjustments'
     */
    @Test
    public void lineItemSubtotalWithOrderAdjustmentsTest() {
        // TODO: test lineItemSubtotalWithOrderAdjustments
    }

    /**
     * Test the property 'discountedSubtotal'
     */
    @Test
    public void discountedSubtotalTest() {
        // TODO: test discountedSubtotal
    }

    /**
     * Test the property 'onetimeProducts'
     */
    @Test
    public void onetimeProductsTest() {
        // TODO: test onetimeProducts
    }

    /**
     * Test the property 'onetimeShippingMethod'
     */
    @Test
    public void onetimeShippingMethodTest() {
        // TODO: test onetimeShippingMethod
    }

    /**
     * Test the property 'nextOrderDateOffsetCounter'
     */
    @Test
    public void nextOrderDateOffsetCounterTest() {
        // TODO: test nextOrderDateOffsetCounter
    }

    /**
     * Test the property 'subscriptionSkipCounter'
     */
    @Test
    public void subscriptionSkipCounterTest() {
        // TODO: test subscriptionSkipCounter
    }

    /**
     * Test the property 'isDraft'
     */
    @Test
    public void isDraftTest() {
        // TODO: test isDraft
    }

    /**
     * Test the property 'hasDraft'
     */
    @Test
    public void hasDraftTest() {
        // TODO: test hasDraft
    }

    /**
     * Test the property 'isPartialDraft'
     */
    @Test
    public void isPartialDraftTest() {
        // TODO: test isPartialDraft
    }

    /**
     * Test the property 'isOrderReminderEmailSent'
     */
    @Test
    public void isOrderReminderEmailSentTest() {
        // TODO: test isOrderReminderEmailSent
    }

    /**
     * Test the property 'isReactivationReminderEmailSent'
     */
    @Test
    public void isReactivationReminderEmailSentTest() {
        // TODO: test isReactivationReminderEmailSent
    }

    /**
     * Test the property 'reactivationDate'
     */
    @Test
    public void reactivationDateTest() {
        // TODO: test reactivationDate
    }

    /**
     * Test the property 'subscriptionPauseDate'
     */
    @Test
    public void subscriptionPauseDateTest() {
        // TODO: test subscriptionPauseDate
    }

}
