/*
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.orderrouting.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AssignmentSuggestion
 */
public class AssignmentSuggestionTest {
    private final AssignmentSuggestion model = new AssignmentSuggestion();

    /**
     * Model tests for AssignmentSuggestion
     */
    @Test
    public void testAssignmentSuggestion() {
        // TODO: test AssignmentSuggestion
    }

    /**
     * Test the property 'futureDate'
     */
    @Test
    public void futureDateTest() {
        // TODO: test futureDate
    }

    /**
     * Test the property 'futureDateString'
     */
    @Test
    public void futureDateStringTest() {
        // TODO: test futureDateString
    }

    /**
     * Test the property 'locationCode'
     */
    @Test
    public void locationCodeTest() {
        // TODO: test locationCode
    }

    /**
     * Test the property 'locationID'
     */
    @Test
    public void locationIDTest() {
        // TODO: test locationID
    }

    /**
     * Test the property 'orderItemID'
     */
    @Test
    public void orderItemIDTest() {
        // TODO: test orderItemID
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'route'
     */
    @Test
    public void routeTest() {
        // TODO: test route
    }

}
