/*
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.orderrouting.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.orderrouting.models.CandidateSuggestionFutureInventory;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CandidateSuggestionInventory
 */
public class CandidateSuggestionInventoryTest {
    private final CandidateSuggestionInventory model = new CandidateSuggestionInventory();

    /**
     * Model tests for CandidateSuggestionInventory
     */
    @Test
    public void testCandidateSuggestionInventory() {
        // TODO: test CandidateSuggestionInventory
    }

    /**
     * Test the property 'available'
     */
    @Test
    public void availableTest() {
        // TODO: test available
    }

    /**
     * Test the property 'futureInventory'
     */
    @Test
    public void futureInventoryTest() {
        // TODO: test futureInventory
    }

    /**
     * Test the property 'partNumber'
     */
    @Test
    public void partNumberTest() {
        // TODO: test partNumber
    }

    /**
     * Test the property 'sku'
     */
    @Test
    public void skuTest() {
        // TODO: test sku
    }

    /**
     * Test the property 'upc'
     */
    @Test
    public void upcTest() {
        // TODO: test upc
    }

}
