/*
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.orderrouting.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.orderrouting.models.AbstractFilter;
import com.kibocommerce.sdk.orderrouting.models.FulfillmentLimit;
import com.kibocommerce.sdk.orderrouting.models.GroupAfterAction;
import com.kibocommerce.sdk.orderrouting.models.LocationSort;
import com.kibocommerce.sdk.orderrouting.models.RankedLocation;
import com.kibocommerce.sdk.orderrouting.models.UserContextInformation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LocationGroupModel
 */
public class LocationGroupModelTest {
    private final LocationGroupModel model = new LocationGroupModel();

    /**
     * Model tests for LocationGroupModel
     */
    @Test
    public void testLocationGroupModel() {
        // TODO: test LocationGroupModel
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'afterActionNone'
     */
    @Test
    public void afterActionNoneTest() {
        // TODO: test afterActionNone
    }

    /**
     * Test the property 'afterActionPartial'
     */
    @Test
    public void afterActionPartialTest() {
        // TODO: test afterActionPartial
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'creatorUsername'
     */
    @Test
    public void creatorUsernameTest() {
        // TODO: test creatorUsername
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'environmentID'
     */
    @Test
    public void environmentIDTest() {
        // TODO: test environmentID
    }

    /**
     * Test the property 'excludedLocationsFromDefaultGroup'
     */
    @Test
    public void excludedLocationsFromDefaultGroupTest() {
        // TODO: test excludedLocationsFromDefaultGroup
    }

    /**
     * Test the property 'filters'
     */
    @Test
    public void filtersTest() {
        // TODO: test filters
    }

    /**
     * Test the property 'fulfillmentLimit'
     */
    @Test
    public void fulfillmentLimitTest() {
        // TODO: test fulfillmentLimit
    }

    /**
     * Test the property 'groupID'
     */
    @Test
    public void groupIDTest() {
        // TODO: test groupID
    }

    /**
     * Test the property 'isDefaultGroup'
     */
    @Test
    public void isDefaultGroupTest() {
        // TODO: test isDefaultGroup
    }

    /**
     * Test the property 'locationIDs'
     */
    @Test
    public void locationIDsTest() {
        // TODO: test locationIDs
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'pathString'
     */
    @Test
    public void pathStringTest() {
        // TODO: test pathString
    }

    /**
     * Test the property 'persisted'
     */
    @Test
    public void persistedTest() {
        // TODO: test persisted
    }

    /**
     * Test the property 'rank'
     */
    @Test
    public void rankTest() {
        // TODO: test rank
    }

    /**
     * Test the property 'rankedLocations'
     */
    @Test
    public void rankedLocationsTest() {
        // TODO: test rankedLocations
    }

    /**
     * Test the property 'routeID'
     */
    @Test
    public void routeIDTest() {
        // TODO: test routeID
    }

    /**
     * Test the property 'siteID'
     */
    @Test
    public void siteIDTest() {
        // TODO: test siteID
    }

    /**
     * Test the property 'sorts'
     */
    @Test
    public void sortsTest() {
        // TODO: test sorts
    }

    /**
     * Test the property 'tenantID'
     */
    @Test
    public void tenantIDTest() {
        // TODO: test tenantID
    }

    /**
     * Test the property 'updated'
     */
    @Test
    public void updatedTest() {
        // TODO: test updated
    }

    /**
     * Test the property 'updaterUsername'
     */
    @Test
    public void updaterUsernameTest() {
        // TODO: test updaterUsername
    }

    /**
     * Test the property 'useRetailerExclusionList'
     */
    @Test
    public void useRetailerExclusionListTest() {
        // TODO: test useRetailerExclusionList
    }

    /**
     * Test the property 'userContext'
     */
    @Test
    public void userContextTest() {
        // TODO: test userContext
    }

}
