/*
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.orderrouting.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.orderrouting.models.LocationCriteriaSetDataDefinition;
import com.kibocommerce.sdk.orderrouting.models.UserContextInformation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LocationCriteriaSet
 */
public class LocationCriteriaSetTest {
    private final LocationCriteriaSet model = new LocationCriteriaSet();

    /**
     * Model tests for LocationCriteriaSet
     */
    @Test
    public void testLocationCriteriaSet() {
        // TODO: test LocationCriteriaSet
    }

    /**
     * Test the property 'columnDefinitions'
     */
    @Test
    public void columnDefinitionsTest() {
        // TODO: test columnDefinitions
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'creatorUsername'
     */
    @Test
    public void creatorUsernameTest() {
        // TODO: test creatorUsername
    }

    /**
     * Test the property 'environmentID'
     */
    @Test
    public void environmentIDTest() {
        // TODO: test environmentID
    }

    /**
     * Test the property 'fileName'
     */
    @Test
    public void fileNameTest() {
        // TODO: test fileName
    }

    /**
     * Test the property 'locationCriteriaSetID'
     */
    @Test
    public void locationCriteriaSetIDTest() {
        // TODO: test locationCriteriaSetID
    }

    /**
     * Test the property 'pathString'
     */
    @Test
    public void pathStringTest() {
        // TODO: test pathString
    }

    /**
     * Test the property 'persisted'
     */
    @Test
    public void persistedTest() {
        // TODO: test persisted
    }

    /**
     * Test the property 'readyState'
     */
    @Test
    public void readyStateTest() {
        // TODO: test readyState
    }

    /**
     * Test the property 'siteID'
     */
    @Test
    public void siteIDTest() {
        // TODO: test siteID
    }

    /**
     * Test the property 'tenantID'
     */
    @Test
    public void tenantIDTest() {
        // TODO: test tenantID
    }

    /**
     * Test the property 'updated'
     */
    @Test
    public void updatedTest() {
        // TODO: test updated
    }

    /**
     * Test the property 'updaterUsername'
     */
    @Test
    public void updaterUsernameTest() {
        // TODO: test updaterUsername
    }

    /**
     * Test the property 'userContext'
     */
    @Test
    public void userContextTest() {
        // TODO: test userContext
    }

}
