/*
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.orderrouting.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.orderrouting.models.ApiDocumentationOrderItem;
import com.kibocommerce.sdk.orderrouting.models.ExclusionListEntryLocationCode;
import com.kibocommerce.sdk.orderrouting.models.ExtendedCustomerInfo;
import com.kibocommerce.sdk.orderrouting.models.ExtendedOrderInfo;
import com.kibocommerce.sdk.orderrouting.models.ShippingAddress;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SuggestionRequest
 */
public class SuggestionRequestTest {
    private final SuggestionRequest model = new SuggestionRequest();

    /**
     * Model tests for SuggestionRequest
     */
    @Test
    public void testSuggestionRequest() {
        // TODO: test SuggestionRequest
    }

    /**
     * Test the property 'bundlingStrategy'
     */
    @Test
    public void bundlingStrategyTest() {
        // TODO: test bundlingStrategy
    }

    /**
     * Test the property 'cartID'
     */
    @Test
    public void cartIDTest() {
        // TODO: test cartID
    }

    /**
     * Test the property 'customData'
     */
    @Test
    public void customDataTest() {
        // TODO: test customData
    }

    /**
     * Test the property 'environmentID'
     */
    @Test
    public void environmentIDTest() {
        // TODO: test environmentID
    }

    /**
     * Test the property 'exclusionListLocationCode'
     */
    @Test
    public void exclusionListLocationCodeTest() {
        // TODO: test exclusionListLocationCode
    }

    /**
     * Test the property 'extendedCustomerInfo'
     */
    @Test
    public void extendedCustomerInfoTest() {
        // TODO: test extendedCustomerInfo
    }

    /**
     * Test the property 'extendedOrderInfo'
     */
    @Test
    public void extendedOrderInfoTest() {
        // TODO: test extendedOrderInfo
    }

    /**
     * Test the property 'externalResponseID'
     */
    @Test
    public void externalResponseIDTest() {
        // TODO: test externalResponseID
    }

    /**
     * Test the property 'fraud'
     */
    @Test
    public void fraudTest() {
        // TODO: test fraud
    }

    /**
     * Test the property 'futureDateLimit'
     */
    @Test
    public void futureDateLimitTest() {
        // TODO: test futureDateLimit
    }

    /**
     * Test the property 'futureExclusionListLocationCode'
     */
    @Test
    public void futureExclusionListLocationCodeTest() {
        // TODO: test futureExclusionListLocationCode
    }

    /**
     * Test the property 'inventoryRequestType'
     */
    @Test
    public void inventoryRequestTypeTest() {
        // TODO: test inventoryRequestType
    }

    /**
     * Test the property 'isExpress'
     */
    @Test
    public void isExpressTest() {
        // TODO: test isExpress
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'locationCodeWhiteList'
     */
    @Test
    public void locationCodeWhiteListTest() {
        // TODO: test locationCodeWhiteList
    }

    /**
     * Test the property 'numShipmentsNotInRequest'
     */
    @Test
    public void numShipmentsNotInRequestTest() {
        // TODO: test numShipmentsNotInRequest
    }

    /**
     * Test the property 'orderID'
     */
    @Test
    public void orderIDTest() {
        // TODO: test orderID
    }

    /**
     * Test the property 'orderType'
     */
    @Test
    public void orderTypeTest() {
        // TODO: test orderType
    }

    /**
     * Test the property 'pickupLocationCode'
     */
    @Test
    public void pickupLocationCodeTest() {
        // TODO: test pickupLocationCode
    }

    /**
     * Test the property 'shippingAddress'
     */
    @Test
    public void shippingAddressTest() {
        // TODO: test shippingAddress
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

}
