/*
 * Kibo ShippingRuntime Service
 * OpenAPI Spec for Kibo ShippingRuntime Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.shippingstorefront.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.shippingstorefront.models.Notification;
import com.kibocommerce.sdk.shippingstorefront.models.ShippingRuntimeManifestShipment;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ManifestResponse
 */
public class ManifestResponseTest {
    private final ManifestResponse model = new ManifestResponse();

    /**
     * Model tests for ManifestResponse
     */
    @Test
    public void testManifestResponse() {
        // TODO: test ManifestResponse
    }

    /**
     * Test the property 'manifestId'
     */
    @Test
    public void manifestIdTest() {
        // TODO: test manifestId
    }

    /**
     * Test the property 'manifestUrl'
     */
    @Test
    public void manifestUrlTest() {
        // TODO: test manifestUrl
    }

    /**
     * Test the property 'carrierId'
     */
    @Test
    public void carrierIdTest() {
        // TODO: test carrierId
    }

    /**
     * Test the property 'locationCode'
     */
    @Test
    public void locationCodeTest() {
        // TODO: test locationCode
    }

    /**
     * Test the property 'includedShipments'
     */
    @Test
    public void includedShipmentsTest() {
        // TODO: test includedShipments
    }

    /**
     * Test the property 'messages'
     */
    @Test
    public void messagesTest() {
        // TODO: test messages
    }

    /**
     * Test the property 'isSuccessful'
     */
    @Test
    public void isSuccessfulTest() {
        // TODO: test isSuccessful
    }

}
