/*
 * Kibo ShippingRuntime Service
 * OpenAPI Spec for Kibo ShippingRuntime Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.shippingstorefront.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.shippingstorefront.models.RatesResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RatesResponseGroup
 */
public class RatesResponseGroupTest {
    private final RatesResponseGroup model = new RatesResponseGroup();

    /**
     * Model tests for RatesResponseGroup
     */
    @Test
    public void testRatesResponseGroup() {
        // TODO: test RatesResponseGroup
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'ratesResponse'
     */
    @Test
    public void ratesResponseTest() {
        // TODO: test ratesResponse
    }

    /**
     * Test the property 'componentRates'
     */
    @Test
    public void componentRatesTest() {
        // TODO: test componentRates
    }

}
