/*
 * Kibo ShippingRuntime Service
 * OpenAPI Spec for Kibo ShippingRuntime Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.shippingstorefront.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ShippingRuntimeManifestShipment
 */
public class ShippingRuntimeManifestShipmentTest {
    private final ShippingRuntimeManifestShipment model = new ShippingRuntimeManifestShipment();

    /**
     * Model tests for ShippingRuntimeManifestShipment
     */
    @Test
    public void testShippingRuntimeManifestShipment() {
        // TODO: test ShippingRuntimeManifestShipment
    }

    /**
     * Test the property 'shipmentNumber'
     */
    @Test
    public void shipmentNumberTest() {
        // TODO: test shipmentNumber
    }

    /**
     * Test the property 'integratorIds'
     */
    @Test
    public void integratorIdsTest() {
        // TODO: test integratorIds
    }

}
