/*
 * Kibo ShippingRuntime Service
 * OpenAPI Spec for Kibo ShippingRuntime Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.shippingstorefront.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ShippingLabel
 */
public class ShippingLabelTest {
    private final ShippingLabel model = new ShippingLabel();

    /**
     * Model tests for ShippingLabel
     */
    @Test
    public void testShippingLabel() {
        // TODO: test ShippingLabel
    }

    /**
     * Test the property 'imageFormat'
     */
    @Test
    public void imageFormatTest() {
        // TODO: test imageFormat
    }

    /**
     * Test the property 'imageData'
     */
    @Test
    public void imageDataTest() {
        // TODO: test imageData
    }

    /**
     * Test the property 'labelUrl'
     */
    @Test
    public void labelUrlTest() {
        // TODO: test labelUrl
    }

}
