/*
 * Kibo ShippingRuntime Service
 * OpenAPI Spec for Kibo ShippingRuntime Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.shippingstorefront.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.shippingstorefront.models.CustomAttribute;
import com.kibocommerce.sdk.shippingstorefront.models.CustomerReferences;
import com.kibocommerce.sdk.shippingstorefront.models.ShippingRuntimeShipment;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ShipmentRequest
 */
public class ShipmentRequestTest {
    private final ShipmentRequest model = new ShipmentRequest();

    /**
     * Model tests for ShipmentRequest
     */
    @Test
    public void testShipmentRequest() {
        // TODO: test ShipmentRequest
    }

    /**
     * Test the property 'isoCurrencyCode'
     */
    @Test
    public void isoCurrencyCodeTest() {
        // TODO: test isoCurrencyCode
    }

    /**
     * Test the property 'shipment'
     */
    @Test
    public void shipmentTest() {
        // TODO: test shipment
    }

    /**
     * Test the property 'customAttributes'
     */
    @Test
    public void customAttributesTest() {
        // TODO: test customAttributes
    }

    /**
     * Test the property 'carrierId'
     */
    @Test
    public void carrierIdTest() {
        // TODO: test carrierId
    }

    /**
     * Test the property 'shippingServiceType'
     */
    @Test
    public void shippingServiceTypeTest() {
        // TODO: test shippingServiceType
    }

    /**
     * Test the property 'shipmentRequestType'
     */
    @Test
    public void shipmentRequestTypeTest() {
        // TODO: test shipmentRequestType
    }

    /**
     * Test the property 'requiresSignature'
     */
    @Test
    public void requiresSignatureTest() {
        // TODO: test requiresSignature
    }

    /**
     * Test the property 'labelFormat'
     */
    @Test
    public void labelFormatTest() {
        // TODO: test labelFormat
    }

    /**
     * Test the property 'customerReferences'
     */
    @Test
    public void customerReferencesTest() {
        // TODO: test customerReferences
    }

}
