/*
 * Kibo Catalog Admin Services
 * OpenAPI Spec for Kibo Catalog Admin Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogadministration.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AttributeSearchSettings
 */
public class AttributeSearchSettingsTest {
    private final AttributeSearchSettings model = new AttributeSearchSettings();

    /**
     * Model tests for AttributeSearchSettings
     */
    @Test
    public void testAttributeSearchSettings() {
        // TODO: test AttributeSearchSettings
    }

    /**
     * Test the property 'searchableInStorefront'
     */
    @Test
    public void searchableInStorefrontTest() {
        // TODO: test searchableInStorefront
    }

    /**
     * Test the property 'searchableInAdmin'
     */
    @Test
    public void searchableInAdminTest() {
        // TODO: test searchableInAdmin
    }

    /**
     * Test the property 'searchDisplayValue'
     */
    @Test
    public void searchDisplayValueTest() {
        // TODO: test searchDisplayValue
    }

    /**
     * Test the property 'allowFilteringAndSortingInStorefront'
     */
    @Test
    public void allowFilteringAndSortingInStorefrontTest() {
        // TODO: test allowFilteringAndSortingInStorefront
    }

    /**
     * Test the property 'indexValueWithCase'
     */
    @Test
    public void indexValueWithCaseTest() {
        // TODO: test indexValueWithCase
    }

    /**
     * Test the property 'customWeightInStorefrontSearch'
     */
    @Test
    public void customWeightInStorefrontSearchTest() {
        // TODO: test customWeightInStorefrontSearch
    }

}
