/*
 * Kibo Catalog Admin Services
 * OpenAPI Spec for Kibo Catalog Admin Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogadministration.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.catalogadministration.models.AdminUserAuditInfo;
import com.kibocommerce.sdk.catalogadministration.models.CatalogAdminsCategoryAttribute;
import com.kibocommerce.sdk.catalogadministration.models.CategoryLocalizedContent;
import com.kibocommerce.sdk.catalogadministration.models.DynamicExpression;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CatalogAdminsCategory
 */
public class CatalogAdminsCategoryTest {
    private final CatalogAdminsCategory model = new CatalogAdminsCategory();

    /**
     * Model tests for CatalogAdminsCategory
     */
    @Test
    public void testCatalogAdminsCategory() {
        // TODO: test CatalogAdminsCategory
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'categoryType'
     */
    @Test
    public void categoryTypeTest() {
        // TODO: test categoryType
    }

    /**
     * Test the property 'catalogId'
     */
    @Test
    public void catalogIdTest() {
        // TODO: test catalogId
    }

    /**
     * Test the property 'parentCategoryId'
     */
    @Test
    public void parentCategoryIdTest() {
        // TODO: test parentCategoryId
    }

    /**
     * Test the property 'parentCategoryCode'
     */
    @Test
    public void parentCategoryCodeTest() {
        // TODO: test parentCategoryCode
    }

    /**
     * Test the property 'parentCategoryName'
     */
    @Test
    public void parentCategoryNameTest() {
        // TODO: test parentCategoryName
    }

    /**
     * Test the property 'parentIsActive'
     */
    @Test
    public void parentIsActiveTest() {
        // TODO: test parentIsActive
    }

    /**
     * Test the property 'categoryCode'
     */
    @Test
    public void categoryCodeTest() {
        // TODO: test categoryCode
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    public void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property 'isDisplayed'
     */
    @Test
    public void isDisplayedTest() {
        // TODO: test isDisplayed
    }

    /**
     * Test the property 'sequence'
     */
    @Test
    public void sequenceTest() {
        // TODO: test sequence
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'dynamicExpression'
     */
    @Test
    public void dynamicExpressionTest() {
        // TODO: test dynamicExpression
    }

    /**
     * Test the property 'productCount'
     */
    @Test
    public void productCountTest() {
        // TODO: test productCount
    }

    /**
     * Test the property 'childCount'
     */
    @Test
    public void childCountTest() {
        // TODO: test childCount
    }

    /**
     * Test the property 'auditInfo'
     */
    @Test
    public void auditInfoTest() {
        // TODO: test auditInfo
    }

    /**
     * Test the property 'shouldSlice'
     */
    @Test
    public void shouldSliceTest() {
        // TODO: test shouldSlice
    }

    /**
     * Test the property 'activeDateStart'
     */
    @Test
    public void activeDateStartTest() {
        // TODO: test activeDateStart
    }

    /**
     * Test the property 'activeDateEnd'
     */
    @Test
    public void activeDateEndTest() {
        // TODO: test activeDateEnd
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

}
