/*
 * Kibo Catalog Admin Services
 * OpenAPI Spec for Kibo Catalog Admin Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogadministration.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.catalogadministration.models.CatalogAdminsAttributeVocabularyValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CatalogAdminsProductOptionValue
 */
public class CatalogAdminsProductOptionValueTest {
    private final CatalogAdminsProductOptionValue model = new CatalogAdminsProductOptionValue();

    /**
     * Model tests for CatalogAdminsProductOptionValue
     */
    @Test
    public void testCatalogAdminsProductOptionValue() {
        // TODO: test CatalogAdminsProductOptionValue
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'attributeVocabularyValueDetail'
     */
    @Test
    public void attributeVocabularyValueDetailTest() {
        // TODO: test attributeVocabularyValueDetail
    }

}
