/*
 * Kibo Catalog Admin Services
 * OpenAPI Spec for Kibo Catalog Admin Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogadministration.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.catalogadministration.models.CatalogAdminsProductImageGroupTag;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CatalogAdminsProductImageGroup
 */
public class CatalogAdminsProductImageGroupTest {
    private final CatalogAdminsProductImageGroup model = new CatalogAdminsProductImageGroup();

    /**
     * Model tests for CatalogAdminsProductImageGroup
     */
    @Test
    public void testCatalogAdminsProductImageGroup() {
        // TODO: test CatalogAdminsProductImageGroup
    }

    /**
     * Test the property 'productImageGroupId'
     */
    @Test
    public void productImageGroupIdTest() {
        // TODO: test productImageGroupId
    }

    /**
     * Test the property 'productImageGroupTags'
     */
    @Test
    public void productImageGroupTagsTest() {
        // TODO: test productImageGroupTags
    }

}
