/*
 * Kibo Catalog Admin Services
 * OpenAPI Spec for Kibo Catalog Admin Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogadministration.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CatalogAdminsTag
 */
public class CatalogAdminsTagTest {
    private final CatalogAdminsTag model = new CatalogAdminsTag();

    /**
     * Model tests for CatalogAdminsTag
     */
    @Test
    public void testCatalogAdminsTag() {
        // TODO: test CatalogAdminsTag
    }

    /**
     * Test the property 'tagCode'
     */
    @Test
    public void tagCodeTest() {
        // TODO: test tagCode
    }

    /**
     * Test the property 'tagName'
     */
    @Test
    public void tagNameTest() {
        // TODO: test tagName
    }

    /**
     * Test the property 'tagPath'
     */
    @Test
    public void tagPathTest() {
        // TODO: test tagPath
    }

}
