/*
 * Kibo Catalog Admin Services
 * OpenAPI Spec for Kibo Catalog Admin Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogadministration.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ContinuityRecurrenceSettings
 */
public class ContinuityRecurrenceSettingsTest {
    private final ContinuityRecurrenceSettings model = new ContinuityRecurrenceSettings();

    /**
     * Model tests for ContinuityRecurrenceSettings
     */
    @Test
    public void testContinuityRecurrenceSettings() {
        // TODO: test ContinuityRecurrenceSettings
    }

    /**
     * Test the property 'startOrdinal'
     */
    @Test
    public void startOrdinalTest() {
        // TODO: test startOrdinal
    }

    /**
     * Test the property 'interval'
     */
    @Test
    public void intervalTest() {
        // TODO: test interval
    }

    /**
     * Test the property 'stopOrdinal'
     */
    @Test
    public void stopOrdinalTest() {
        // TODO: test stopOrdinal
    }

}
