/*
 * Kibo Catalog Admin Services
 * OpenAPI Spec for Kibo Catalog Admin Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogadministration.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.catalogadministration.models.AdminUserAuditInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CouponSet
 */
public class CouponSetTest {
    private final CouponSet model = new CouponSet();

    /**
     * Model tests for CouponSet
     */
    @Test
    public void testCouponSet() {
        // TODO: test CouponSet
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'couponSetCode'
     */
    @Test
    public void couponSetCodeTest() {
        // TODO: test couponSetCode
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'couponCodeType'
     */
    @Test
    public void couponCodeTypeTest() {
        // TODO: test couponCodeType
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'canBeDeleted'
     */
    @Test
    public void canBeDeletedTest() {
        // TODO: test canBeDeleted
    }

    /**
     * Test the property 'maxRedemptionsPerUser'
     */
    @Test
    public void maxRedemptionsPerUserTest() {
        // TODO: test maxRedemptionsPerUser
    }

    /**
     * Test the property 'maxRedemptionsPerCouponCode'
     */
    @Test
    public void maxRedemptionsPerCouponCodeTest() {
        // TODO: test maxRedemptionsPerCouponCode
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'auditInfo'
     */
    @Test
    public void auditInfoTest() {
        // TODO: test auditInfo
    }

    /**
     * Test the property 'setSize'
     */
    @Test
    public void setSizeTest() {
        // TODO: test setSize
    }

    /**
     * Test the property 'couponCodeCount'
     */
    @Test
    public void couponCodeCountTest() {
        // TODO: test couponCodeCount
    }

    /**
     * Test the property 'redemptionCount'
     */
    @Test
    public void redemptionCountTest() {
        // TODO: test redemptionCount
    }

    /**
     * Test the property 'assignedDiscountCount'
     */
    @Test
    public void assignedDiscountCountTest() {
        // TODO: test assignedDiscountCount
    }

}
