/*
 * Kibo Catalog Admin Services
 * OpenAPI Spec for Kibo Catalog Admin Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogadministration.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProductTypeChangeRequest
 */
public class ProductTypeChangeRequestTest {
    private final ProductTypeChangeRequest model = new ProductTypeChangeRequest();

    /**
     * Model tests for ProductTypeChangeRequest
     */
    @Test
    public void testProductTypeChangeRequest() {
        // TODO: test ProductTypeChangeRequest
    }

    /**
     * Test the property 'targetProductTypeId'
     */
    @Test
    public void targetProductTypeIdTest() {
        // TODO: test targetProductTypeId
    }

    /**
     * Test the property 'ignoreDataLoss'
     */
    @Test
    public void ignoreDataLossTest() {
        // TODO: test ignoreDataLoss
    }

    /**
     * Test the property 'testMode'
     */
    @Test
    public void testModeTest() {
        // TODO: test testMode
    }

    /**
     * Test the property 'shouldFailFast'
     */
    @Test
    public void shouldFailFastTest() {
        // TODO: test shouldFailFast
    }

}
