/*
 * Kibo Catalog Admin Services
 * OpenAPI Spec for Kibo Catalog Admin Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogadministration.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.catalogadministration.models.AdminUserAuditInfo;
import com.kibocommerce.sdk.catalogadministration.models.ProductSortExpression;
import com.kibocommerce.sdk.catalogadministration.models.ProductSortOverride;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProductSortDefinition
 */
public class ProductSortDefinitionTest {
    private final ProductSortDefinition model = new ProductSortDefinition();

    /**
     * Model tests for ProductSortDefinition
     */
    @Test
    public void testProductSortDefinition() {
        // TODO: test ProductSortDefinition
    }

    /**
     * Test the property 'productSortDefinitionId'
     */
    @Test
    public void productSortDefinitionIdTest() {
        // TODO: test productSortDefinitionId
    }

    /**
     * Test the property 'categoryId'
     */
    @Test
    public void categoryIdTest() {
        // TODO: test categoryId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'sortExpressions'
     */
    @Test
    public void sortExpressionsTest() {
        // TODO: test sortExpressions
    }

    /**
     * Test the property 'boosted'
     */
    @Test
    public void boostedTest() {
        // TODO: test boosted
    }

    /**
     * Test the property 'buried'
     */
    @Test
    public void buriedTest() {
        // TODO: test buried
    }

    /**
     * Test the property 'auditInfo'
     */
    @Test
    public void auditInfoTest() {
        // TODO: test auditInfo
    }

}
