/*
 * Kibo Catalog Admin Services
 * OpenAPI Spec for Kibo Catalog Admin Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogadministration.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProductPublishingInfo
 */
public class ProductPublishingInfoTest {
    private final ProductPublishingInfo model = new ProductPublishingInfo();

    /**
     * Model tests for ProductPublishingInfo
     */
    @Test
    public void testProductPublishingInfo() {
        // TODO: test ProductPublishingInfo
    }

    /**
     * Test the property 'publishedState'
     */
    @Test
    public void publishedStateTest() {
        // TODO: test publishedState
    }

    /**
     * Test the property 'lastPublishedBy'
     */
    @Test
    public void lastPublishedByTest() {
        // TODO: test lastPublishedBy
    }

    /**
     * Test the property 'lastPublishedDate'
     */
    @Test
    public void lastPublishedDateTest() {
        // TODO: test lastPublishedDate
    }

    /**
     * Test the property 'publishSetCode'
     */
    @Test
    public void publishSetCodeTest() {
        // TODO: test publishSetCode
    }

}
