/*
 * Kibo Catalog Admin Services
 * OpenAPI Spec for Kibo Catalog Admin Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogadministration.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProductLocalizedSEOContent
 */
public class ProductLocalizedSEOContentTest {
    private final ProductLocalizedSEOContent model = new ProductLocalizedSEOContent();

    /**
     * Model tests for ProductLocalizedSEOContent
     */
    @Test
    public void testProductLocalizedSEOContent() {
        // TODO: test ProductLocalizedSEOContent
    }

    /**
     * Test the property 'localeCode'
     */
    @Test
    public void localeCodeTest() {
        // TODO: test localeCode
    }

    /**
     * Test the property 'metaTagTitle'
     */
    @Test
    public void metaTagTitleTest() {
        // TODO: test metaTagTitle
    }

    /**
     * Test the property 'metaTagDescription'
     */
    @Test
    public void metaTagDescriptionTest() {
        // TODO: test metaTagDescription
    }

    /**
     * Test the property 'metaTagKeywords'
     */
    @Test
    public void metaTagKeywordsTest() {
        // TODO: test metaTagKeywords
    }

    /**
     * Test the property 'titleTagTitle'
     */
    @Test
    public void titleTagTitleTest() {
        // TODO: test titleTagTitle
    }

    /**
     * Test the property 'seoFriendlyUrl'
     */
    @Test
    public void seoFriendlyUrlTest() {
        // TODO: test seoFriendlyUrl
    }

}
