/*
 * Kibo Catalog Admin Services
 * OpenAPI Spec for Kibo Catalog Admin Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogadministration.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProductVariationFixedPrice
 */
public class ProductVariationFixedPriceTest {
    private final ProductVariationFixedPrice model = new ProductVariationFixedPrice();

    /**
     * Model tests for ProductVariationFixedPrice
     */
    @Test
    public void testProductVariationFixedPrice() {
        // TODO: test ProductVariationFixedPrice
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'listPrice'
     */
    @Test
    public void listPriceTest() {
        // TODO: test listPrice
    }

    /**
     * Test the property 'salePrice'
     */
    @Test
    public void salePriceTest() {
        // TODO: test salePrice
    }

    /**
     * Test the property 'msrp'
     */
    @Test
    public void msrpTest() {
        // TODO: test msrp
    }

    /**
     * Test the property 'creditValue'
     */
    @Test
    public void creditValueTest() {
        // TODO: test creditValue
    }

}
