/*
 * Kibo PricingRuntime Service
 * OpenAPI Spec for Kibo PricingRuntime Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.pricingstorefront.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AutoAddDiscountTarget
 */
public class AutoAddDiscountTargetTest {
    private final AutoAddDiscountTarget model = new AutoAddDiscountTarget();

    /**
     * Model tests for AutoAddDiscountTarget
     */
    @Test
    public void testAutoAddDiscountTarget() {
        // TODO: test AutoAddDiscountTarget
    }

    /**
     * Test the property 'discountId'
     */
    @Test
    public void discountIdTest() {
        // TODO: test discountId
    }

    /**
     * Test the property 'friendlyDescription'
     */
    @Test
    public void friendlyDescriptionTest() {
        // TODO: test friendlyDescription
    }

    /**
     * Test the property 'includedProductCodes'
     */
    @Test
    public void includedProductCodesTest() {
        // TODO: test includedProductCodes
    }

}
