/*
 * Kibo AppDev Service
 * OpenAPI Spec for Kibo AppDev Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.appdevelopment.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AppDevAttribute
 */
public class AppDevAttributeTest {
    private final AppDevAttribute model = new AppDevAttribute();

    /**
     * Model tests for AppDevAttribute
     */
    @Test
    public void testAppDevAttribute() {
        // TODO: test AppDevAttribute
    }

    /**
     * Test the property 'attributeId'
     */
    @Test
    public void attributeIdTest() {
        // TODO: test attributeId
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'fqn'
     */
    @Test
    public void fqnTest() {
        // TODO: test fqn
    }

    /**
     * Test the property 'sequence'
     */
    @Test
    public void sequenceTest() {
        // TODO: test sequence
    }

    /**
     * Test the property 'vocabularyJson'
     */
    @Test
    public void vocabularyJsonTest() {
        // TODO: test vocabularyJson
    }

    /**
     * Test the property 'applicationAttributeId'
     */
    @Test
    public void applicationAttributeIdTest() {
        // TODO: test applicationAttributeId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'inputType'
     */
    @Test
    public void inputTypeTest() {
        // TODO: test inputType
    }

    /**
     * Test the property 'adminName'
     */
    @Test
    public void adminNameTest() {
        // TODO: test adminName
    }

    /**
     * Test the property 'vocabularyValues'
     */
    @Test
    public void vocabularyValuesTest() {
        // TODO: test vocabularyValues
    }

}
