/*
 * Kibo AppDev Service
 * OpenAPI Spec for Kibo AppDev Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.appdevelopment.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.appdevelopment.models.ApplicationAttribute;
import com.kibocommerce.sdk.appdevelopment.models.ApplicationBehavior;
import com.kibocommerce.sdk.appdevelopment.models.ApplicationCapability;
import com.kibocommerce.sdk.appdevelopment.models.ApplicationCapabilityType;
import com.kibocommerce.sdk.appdevelopment.models.ApplicationEntitlement;
import com.kibocommerce.sdk.appdevelopment.models.ApplicationSubscription;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AppDevPackage
 */
public class AppDevPackageTest {
    private final AppDevPackage model = new AppDevPackage();

    /**
     * Model tests for AppDevPackage
     */
    @Test
    public void testAppDevPackage() {
        // TODO: test AppDevPackage
    }

    /**
     * Test the property 'updateDate'
     */
    @Test
    public void updateDateTest() {
        // TODO: test updateDate
    }

    /**
     * Test the property 'applicationUpdateDate'
     */
    @Test
    public void applicationUpdateDateTest() {
        // TODO: test applicationUpdateDate
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'applicationName'
     */
    @Test
    public void applicationNameTest() {
        // TODO: test applicationName
    }

    /**
     * Test the property 'applicationTypeId'
     */
    @Test
    public void applicationTypeIdTest() {
        // TODO: test applicationTypeId
    }

    /**
     * Test the property 'applicationTypeName'
     */
    @Test
    public void applicationTypeNameTest() {
        // TODO: test applicationTypeName
    }

    /**
     * Test the property 'majorVersion'
     */
    @Test
    public void majorVersionTest() {
        // TODO: test majorVersion
    }

    /**
     * Test the property 'minorVersion'
     */
    @Test
    public void minorVersionTest() {
        // TODO: test minorVersion
    }

    /**
     * Test the property 'revision'
     */
    @Test
    public void revisionTest() {
        // TODO: test revision
    }

    /**
     * Test the property 'sharedSecret'
     */
    @Test
    public void sharedSecretTest() {
        // TODO: test sharedSecret
    }

    /**
     * Test the property 'applicationStatusId'
     */
    @Test
    public void applicationStatusIdTest() {
        // TODO: test applicationStatusId
    }

    /**
     * Test the property 'applicationStatusName'
     */
    @Test
    public void applicationStatusNameTest() {
        // TODO: test applicationStatusName
    }

    /**
     * Test the property 'apiVersion'
     */
    @Test
    public void apiVersionTest() {
        // TODO: test apiVersion
    }

    /**
     * Test the property 'applicationDescription'
     */
    @Test
    public void applicationDescriptionTest() {
        // TODO: test applicationDescription
    }

    /**
     * Test the property 'themeEngineVersion'
     */
    @Test
    public void themeEngineVersionTest() {
        // TODO: test themeEngineVersion
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    public void namespaceTest() {
        // TODO: test namespace
    }

    /**
     * Test the property 'validApplicationStatusIdList'
     */
    @Test
    public void validApplicationStatusIdListTest() {
        // TODO: test validApplicationStatusIdList
    }

    /**
     * Test the property 'appSchemeVersion'
     */
    @Test
    public void appSchemeVersionTest() {
        // TODO: test appSchemeVersion
    }

    /**
     * Test the property 'appConfigUrl'
     */
    @Test
    public void appConfigUrlTest() {
        // TODO: test appConfigUrl
    }

    /**
     * Test the property 'isReleasePackage'
     */
    @Test
    public void isReleasePackageTest() {
        // TODO: test isReleasePackage
    }

    /**
     * Test the property 'packageName'
     */
    @Test
    public void packageNameTest() {
        // TODO: test packageName
    }

    /**
     * Test the property 'packageDescription'
     */
    @Test
    public void packageDescriptionTest() {
        // TODO: test packageDescription
    }

    /**
     * Test the property 'dataNamespace'
     */
    @Test
    public void dataNamespaceTest() {
        // TODO: test dataNamespace
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'appId'
     */
    @Test
    public void appIdTest() {
        // TODO: test appId
    }

    /**
     * Test the property 'applicationId'
     */
    @Test
    public void applicationIdTest() {
        // TODO: test applicationId
    }

    /**
     * Test the property 'applicationDetailId'
     */
    @Test
    public void applicationDetailIdTest() {
        // TODO: test applicationDetailId
    }

    /**
     * Test the property 'isLocked'
     */
    @Test
    public void isLockedTest() {
        // TODO: test isLocked
    }

    /**
     * Test the property 'isDeleted'
     */
    @Test
    public void isDeletedTest() {
        // TODO: test isDeleted
    }

    /**
     * Test the property 'assetFileCount'
     */
    @Test
    public void assetFileCountTest() {
        // TODO: test assetFileCount
    }

    /**
     * Test the property 'packageGuid'
     */
    @Test
    public void packageGuidTest() {
        // TODO: test packageGuid
    }

    /**
     * Test the property 'applicationStatus'
     */
    @Test
    public void applicationStatusTest() {
        // TODO: test applicationStatus
    }

    /**
     * Test the property 'applicationBehaviors'
     */
    @Test
    public void applicationBehaviorsTest() {
        // TODO: test applicationBehaviors
    }

    /**
     * Test the property 'applicationSubscriptions'
     */
    @Test
    public void applicationSubscriptionsTest() {
        // TODO: test applicationSubscriptions
    }

    /**
     * Test the property 'applicationCapabilityTypes'
     */
    @Test
    public void applicationCapabilityTypesTest() {
        // TODO: test applicationCapabilityTypes
    }

    /**
     * Test the property 'applicationAttributes'
     */
    @Test
    public void applicationAttributesTest() {
        // TODO: test applicationAttributes
    }

    /**
     * Test the property 'applicationCapabilities'
     */
    @Test
    public void applicationCapabilitiesTest() {
        // TODO: test applicationCapabilities
    }

    /**
     * Test the property 'applicationEntitlements'
     */
    @Test
    public void applicationEntitlementsTest() {
        // TODO: test applicationEntitlements
    }

    /**
     * Test the property 'attributeNamespace'
     */
    @Test
    public void attributeNamespaceTest() {
        // TODO: test attributeNamespace
    }

    /**
     * Test the property 'hasApplicationVersions'
     */
    @Test
    public void hasApplicationVersionsTest() {
        // TODO: test hasApplicationVersions
    }

    /**
     * Test the property 'legacyNamespace'
     */
    @Test
    public void legacyNamespaceTest() {
        // TODO: test legacyNamespace
    }

    /**
     * Test the property 'namespaceRegistryId'
     */
    @Test
    public void namespaceRegistryIdTest() {
        // TODO: test namespaceRegistryId
    }

    /**
     * Test the property 'publishedParentThemeId'
     */
    @Test
    public void publishedParentThemeIdTest() {
        // TODO: test publishedParentThemeId
    }

    /**
     * Test the property 'publishedParentSemanticVersion'
     */
    @Test
    public void publishedParentSemanticVersionTest() {
        // TODO: test publishedParentSemanticVersion
    }

    /**
     * Test the property 'semanticVersionRange'
     */
    @Test
    public void semanticVersionRangeTest() {
        // TODO: test semanticVersionRange
    }

    /**
     * Test the property 'parentThemeName'
     */
    @Test
    public void parentThemeNameTest() {
        // TODO: test parentThemeName
    }

    /**
     * Test the property 'parentThemeAppKey'
     */
    @Test
    public void parentThemeAppKeyTest() {
        // TODO: test parentThemeAppKey
    }

    /**
     * Test the property 'updateParentAppKey'
     */
    @Test
    public void updateParentAppKeyTest() {
        // TODO: test updateParentAppKey
    }

    /**
     * Test the property 'updateAvailable'
     */
    @Test
    public void updateAvailableTest() {
        // TODO: test updateAvailable
    }

    /**
     * Test the property 'appKey'
     */
    @Test
    public void appKeyTest() {
        // TODO: test appKey
    }

    /**
     * Test the property 'updateParentThemeName'
     */
    @Test
    public void updateParentThemeNameTest() {
        // TODO: test updateParentThemeName
    }

    /**
     * Test the property 'updateParentThemeVersion'
     */
    @Test
    public void updateParentThemeVersionTest() {
        // TODO: test updateParentThemeVersion
    }

    /**
     * Test the property 'applicationOwnerDevAccountId'
     */
    @Test
    public void applicationOwnerDevAccountIdTest() {
        // TODO: test applicationOwnerDevAccountId
    }

}
