/*
 * Kibo AppDev Service
 * OpenAPI Spec for Kibo AppDev Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.appdevelopment.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.appdevelopment.models.ApplicationTransaction;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApplicationEntitlement
 */
public class ApplicationEntitlementTest {
    private final ApplicationEntitlement model = new ApplicationEntitlement();

    /**
     * Model tests for ApplicationEntitlement
     */
    @Test
    public void testApplicationEntitlement() {
        // TODO: test ApplicationEntitlement
    }

    /**
     * Test the property 'appKey'
     */
    @Test
    public void appKeyTest() {
        // TODO: test appKey
    }

    /**
     * Test the property 'applicationEntitlementId'
     */
    @Test
    public void applicationEntitlementIdTest() {
        // TODO: test applicationEntitlementId
    }

    /**
     * Test the property 'packageId'
     */
    @Test
    public void packageIdTest() {
        // TODO: test packageId
    }

    /**
     * Test the property 'applicationLicenseType'
     */
    @Test
    public void applicationLicenseTypeTest() {
        // TODO: test applicationLicenseType
    }

    /**
     * Test the property 'entitlementStatus'
     */
    @Test
    public void entitlementStatusTest() {
        // TODO: test entitlementStatus
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'siteId'
     */
    @Test
    public void siteIdTest() {
        // TODO: test siteId
    }

    /**
     * Test the property 'effectiveStartDate'
     */
    @Test
    public void effectiveStartDateTest() {
        // TODO: test effectiveStartDate
    }

    /**
     * Test the property 'effectiveEndDate'
     */
    @Test
    public void effectiveEndDateTest() {
        // TODO: test effectiveEndDate
    }

    /**
     * Test the property 'applicationTransactions'
     */
    @Test
    public void applicationTransactionsTest() {
        // TODO: test applicationTransactions
    }

    /**
     * Test the property 'applicationName'
     */
    @Test
    public void applicationNameTest() {
        // TODO: test applicationName
    }

    /**
     * Test the property 'applicationVersion'
     */
    @Test
    public void applicationVersionTest() {
        // TODO: test applicationVersion
    }

    /**
     * Test the property 'installedByFirstName'
     */
    @Test
    public void installedByFirstNameTest() {
        // TODO: test installedByFirstName
    }

    /**
     * Test the property 'installedByLastName'
     */
    @Test
    public void installedByLastNameTest() {
        // TODO: test installedByLastName
    }

    /**
     * Test the property 'installedDate'
     */
    @Test
    public void installedDateTest() {
        // TODO: test installedDate
    }

    /**
     * Test the property 'packageName'
     */
    @Test
    public void packageNameTest() {
        // TODO: test packageName
    }

    /**
     * Test the property 'tenantName'
     */
    @Test
    public void tenantNameTest() {
        // TODO: test tenantName
    }

    /**
     * Test the property 'applicationStatusId'
     */
    @Test
    public void applicationStatusIdTest() {
        // TODO: test applicationStatusId
    }

    /**
     * Test the property 'applicationId'
     */
    @Test
    public void applicationIdTest() {
        // TODO: test applicationId
    }

    /**
     * Test the property 'devAccountId'
     */
    @Test
    public void devAccountIdTest() {
        // TODO: test devAccountId
    }

    /**
     * Test the property 'installedAppsApplicationId'
     */
    @Test
    public void installedAppsApplicationIdTest() {
        // TODO: test installedAppsApplicationId
    }

    /**
     * Test the property 'appOwnerDevAccountId'
     */
    @Test
    public void appOwnerDevAccountIdTest() {
        // TODO: test appOwnerDevAccountId
    }

}
