/*
 * Kibo AppDev Service
 * OpenAPI Spec for Kibo AppDev Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.appdevelopment.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApplicationCapabilityDomainValue
 */
public class ApplicationCapabilityDomainValueTest {
    private final ApplicationCapabilityDomainValue model = new ApplicationCapabilityDomainValue();

    /**
     * Model tests for ApplicationCapabilityDomainValue
     */
    @Test
    public void testApplicationCapabilityDomainValue() {
        // TODO: test ApplicationCapabilityDomainValue
    }

    /**
     * Test the property 'applicationCapabilityDomainValueId'
     */
    @Test
    public void applicationCapabilityDomainValueIdTest() {
        // TODO: test applicationCapabilityDomainValueId
    }

    /**
     * Test the property 'applicationCapabilityDomainId1'
     */
    @Test
    public void applicationCapabilityDomainId1Test() {
        // TODO: test applicationCapabilityDomainId1
    }

    /**
     * Test the property 'applicationCapabilityDomainId2'
     */
    @Test
    public void applicationCapabilityDomainId2Test() {
        // TODO: test applicationCapabilityDomainId2
    }

    /**
     * Test the property 'valueName'
     */
    @Test
    public void valueNameTest() {
        // TODO: test valueName
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

}
