/*
 * Kibo Content Service
 * OpenAPI Spec for Kibo Content Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.content.api;

import com.kibocommerce.sdk.common.ApiException;
import com.kibocommerce.sdk.content.models.DocumentList;
import com.kibocommerce.sdk.content.models.DocumentListCollection;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DocumentListApi
 */
@Disabled
public class DocumentListApiTest {

    private final DocumentListApi api = new DocumentListApi();

    /**
     * Create DocumentList
     *
     * Create DocumentList
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createDocumentListTest() throws ApiException {
        DocumentList documentList = null;
        DocumentList response = api.createDocumentList(documentList);
        // TODO: test validations
    }

    /**
     * Delete Document List
     *
     * Delete Document List
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteDocumentListTest() throws ApiException {
        String documentListName = null;
        api.deleteDocumentList(documentListName);
        // TODO: test validations
    }

    /**
     * Get Document List
     *
     * Get Document List
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDocumentListTest() throws ApiException {
        String documentListName = null;
        DocumentList response = api.getDocumentList(documentListName);
        // TODO: test validations
    }

    /**
     * Get Document Lists
     *
     * Retrieve a paged documentListName of all document lists
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDocumentListsTest() throws ApiException {
        Integer pageSize = null;
        Integer startIndex = null;
        DocumentListCollection response = api.getDocumentLists(pageSize, startIndex);
        // TODO: test validations
    }

    /**
     * Update Document List
     *
     * Update Document List
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateDocumentListTest() throws ApiException {
        String documentListName = null;
        DocumentList documentList = null;
        DocumentList response = api.updateDocumentList(documentListName, documentList);
        // TODO: test validations
    }

}
