/*
 * Kibo Customer Service
 * OpenAPI Spec for Kibo Customer Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.customer.api;

import com.kibocommerce.sdk.common.ApiException;
import com.kibocommerce.sdk.customer.models.CustomerSet;
import com.kibocommerce.sdk.customer.models.CustomerSetCollection;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CustomerSetApi
 */
@Disabled
public class CustomerSetApiTest {

    private final CustomerSetApi api = new CustomerSetApi();

    /**
     * Get Customer Set
     *
     * Retrieves the name of a customer group specified the customer group ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCustomerSetTest() throws ApiException {
        String code = null;
        CustomerSet response = api.getCustomerSet(code);
        // TODO: test validations
    }

    /**
     * Get Customer Sets
     *
     * Retrieves a list of all customerSets defined for the site according to any specified filter criteria and sort options.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCustomerSetsTest() throws ApiException {
        Integer startIndex = null;
        Integer pageSize = null;
        String sortBy = null;
        String responseGroups = null;
        CustomerSetCollection response = api.getCustomerSets(startIndex, pageSize, sortBy, responseGroups);
        // TODO: test validations
    }

}
