/*
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.inventory.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ExportInventoryRequest
 */
public class ExportInventoryRequestTest {
    private final ExportInventoryRequest model = new ExportInventoryRequest();

    /**
     * Model tests for ExportInventoryRequest
     */
    @Test
    public void testExportInventoryRequest() {
        // TODO: test ExportInventoryRequest
    }

    /**
     * Test the property 'exportSettingsName'
     */
    @Test
    public void exportSettingsNameTest() {
        // TODO: test exportSettingsName
    }

    /**
     * Test the property 'exportSettingsFTPName'
     */
    @Test
    public void exportSettingsFTPNameTest() {
        // TODO: test exportSettingsFTPName
    }

    /**
     * Test the property 'exportSettingsS3Name'
     */
    @Test
    public void exportSettingsS3NameTest() {
        // TODO: test exportSettingsS3Name
    }

    /**
     * Test the property 'development'
     */
    @Test
    public void developmentTest() {
        // TODO: test development
    }

    /**
     * Test the property 'locationCode'
     */
    @Test
    public void locationCodeTest() {
        // TODO: test locationCode
    }

    /**
     * Test the property 'userID'
     */
    @Test
    public void userIDTest() {
        // TODO: test userID
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    public void pageSizeTest() {
        // TODO: test pageSize
    }

    /**
     * Test the property 'pageNum'
     */
    @Test
    public void pageNumTest() {
        // TODO: test pageNum
    }

    /**
     * Test the property 'sortBy'
     */
    @Test
    public void sortByTest() {
        // TODO: test sortBy
    }

}
