/*
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.inventory.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FetchFileConnectionResponse
 */
public class FetchFileConnectionResponseTest {
    private final FetchFileConnectionResponse model = new FetchFileConnectionResponse();

    /**
     * Model tests for FetchFileConnectionResponse
     */
    @Test
    public void testFetchFileConnectionResponse() {
        // TODO: test FetchFileConnectionResponse
    }

    /**
     * Test the property 'ftpFiles'
     */
    @Test
    public void ftpFilesTest() {
        // TODO: test ftpFiles
    }

    /**
     * Test the property 'ftpArchiveFiles'
     */
    @Test
    public void ftpArchiveFilesTest() {
        // TODO: test ftpArchiveFiles
    }

    /**
     * Test the property 's3Files'
     */
    @Test
    public void s3FilesTest() {
        // TODO: test s3Files
    }

    /**
     * Test the property 's3ArchiveFiles'
     */
    @Test
    public void s3ArchiveFilesTest() {
        // TODO: test s3ArchiveFiles
    }

}
