/*
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.inventory.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.inventory.models.ExportSettings;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetExportSettingsResponse
 */
public class GetExportSettingsResponseTest {
    private final GetExportSettingsResponse model = new GetExportSettingsResponse();

    /**
     * Model tests for GetExportSettingsResponse
     */
    @Test
    public void testGetExportSettingsResponse() {
        // TODO: test GetExportSettingsResponse
    }

    /**
     * Test the property 'exportSettings'
     */
    @Test
    public void exportSettingsTest() {
        // TODO: test exportSettings
    }

}
