/*
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.inventory.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InventoryFutureInventory
 */
public class InventoryFutureInventoryTest {
    private final InventoryFutureInventory model = new InventoryFutureInventory();

    /**
     * Model tests for InventoryFutureInventory
     */
    @Test
    public void testInventoryFutureInventory() {
        // TODO: test InventoryFutureInventory
    }

    /**
     * Test the property 'futureInventoryID'
     */
    @Test
    public void futureInventoryIDTest() {
        // TODO: test futureInventoryID
    }

    /**
     * Test the property 'onhand'
     */
    @Test
    public void onhandTest() {
        // TODO: test onhand
    }

    /**
     * Test the property 'available'
     */
    @Test
    public void availableTest() {
        // TODO: test available
    }

    /**
     * Test the property 'allocated'
     */
    @Test
    public void allocatedTest() {
        // TODO: test allocated
    }

    /**
     * Test the property 'pending'
     */
    @Test
    public void pendingTest() {
        // TODO: test pending
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'deliveryDate'
     */
    @Test
    public void deliveryDateTest() {
        // TODO: test deliveryDate
    }

    /**
     * Test the property 'createDate'
     */
    @Test
    public void createDateTest() {
        // TODO: test createDate
    }

}
