/*
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.inventory.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RefreshItem
 */
public class RefreshItemTest {
    private final RefreshItem model = new RefreshItem();

    /**
     * Model tests for RefreshItem
     */
    @Test
    public void testRefreshItem() {
        // TODO: test RefreshItem
    }

    /**
     * Test the property 'partNumber'
     */
    @Test
    public void partNumberTest() {
        // TODO: test partNumber
    }

    /**
     * Test the property 'upc'
     */
    @Test
    public void upcTest() {
        // TODO: test upc
    }

    /**
     * Test the property 'sku'
     */
    @Test
    public void skuTest() {
        // TODO: test sku
    }

    /**
     * Test the property 'binID'
     */
    @Test
    public void binIDTest() {
        // TODO: test binID
    }

    /**
     * Test the property 'LTD'
     */
    @Test
    public void LTDTest() {
        // TODO: test LTD
    }

    /**
     * Test the property 'floor'
     */
    @Test
    public void floorTest() {
        // TODO: test floor
    }

    /**
     * Test the property 'safetyStock'
     */
    @Test
    public void safetyStockTest() {
        // TODO: test safetyStock
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'retailPrice'
     */
    @Test
    public void retailPriceTest() {
        // TODO: test retailPrice
    }

    /**
     * Test the property 'currencyID'
     */
    @Test
    public void currencyIDTest() {
        // TODO: test currencyID
    }

    /**
     * Test the property 'inventoryLocatorName'
     */
    @Test
    public void inventoryLocatorNameTest() {
        // TODO: test inventoryLocatorName
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'deliveryDate'
     */
    @Test
    public void deliveryDateTest() {
        // TODO: test deliveryDate
    }

}
