/*
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.inventory.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ShipmentInventoryAllocationRequest
 */
public class ShipmentInventoryAllocationRequestTest {
    private final ShipmentInventoryAllocationRequest model = new ShipmentInventoryAllocationRequest();

    /**
     * Model tests for ShipmentInventoryAllocationRequest
     */
    @Test
    public void testShipmentInventoryAllocationRequest() {
        // TODO: test ShipmentInventoryAllocationRequest
    }

    /**
     * Test the property 'shipmentIDs'
     */
    @Test
    public void shipmentIDsTest() {
        // TODO: test shipmentIDs
    }

}
