/*
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.inventory.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TenantSiloConfigModel
 */
public class TenantSiloConfigModelTest {
    private final TenantSiloConfigModel model = new TenantSiloConfigModel();

    /**
     * Model tests for TenantSiloConfigModel
     */
    @Test
    public void testTenantSiloConfigModel() {
        // TODO: test TenantSiloConfigModel
    }

    /**
     * Test the property 'siloID'
     */
    @Test
    public void siloIDTest() {
        // TODO: test siloID
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'usable'
     */
    @Test
    public void usableTest() {
        // TODO: test usable
    }

    /**
     * Test the property 'additonalTenantsAllowed'
     */
    @Test
    public void additonalTenantsAllowedTest() {
        // TODO: test additonalTenantsAllowed
    }

    /**
     * Test the property 'batchWorkers'
     */
    @Test
    public void batchWorkersTest() {
        // TODO: test batchWorkers
    }

    /**
     * Test the property 'eventSenderWorkers'
     */
    @Test
    public void eventSenderWorkersTest() {
        // TODO: test eventSenderWorkers
    }

    /**
     * Test the property 'tenantID'
     */
    @Test
    public void tenantIDTest() {
        // TODO: test tenantID
    }

}
