/*
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.inventory.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.inventory.models.TransitionCartItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TransitionCartRequestAllOf
 */
public class TransitionCartRequestAllOfTest {
    private final TransitionCartRequestAllOf model = new TransitionCartRequestAllOf();

    /**
     * Model tests for TransitionCartRequestAllOf
     */
    @Test
    public void testTransitionCartRequestAllOf() {
        // TODO: test TransitionCartRequestAllOf
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'cartID'
     */
    @Test
    public void cartIDTest() {
        // TODO: test cartID
    }

    /**
     * Test the property 'orderID'
     */
    @Test
    public void orderIDTest() {
        // TODO: test orderID
    }

}
