/*
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.inventory.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UpdateExportSettingsS3ResponseAllOf
 */
public class UpdateExportSettingsS3ResponseAllOfTest {
    private final UpdateExportSettingsS3ResponseAllOf model = new UpdateExportSettingsS3ResponseAllOf();

    /**
     * Model tests for UpdateExportSettingsS3ResponseAllOf
     */
    @Test
    public void testUpdateExportSettingsS3ResponseAllOf() {
        // TODO: test UpdateExportSettingsS3ResponseAllOf
    }

    /**
     * Test the property 'tenantID'
     */
    @Test
    public void tenantIDTest() {
        // TODO: test tenantID
    }

    /**
     * Test the property 'exportSettingsS3ID'
     */
    @Test
    public void exportSettingsS3IDTest() {
        // TODO: test exportSettingsS3ID
    }

    /**
     * Test the property 'exportSettingsID'
     */
    @Test
    public void exportSettingsIDTest() {
        // TODO: test exportSettingsID
    }

}
