/*
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.inventory.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UpdateExportSettingsResponseAllOf
 */
public class UpdateExportSettingsResponseAllOfTest {
    private final UpdateExportSettingsResponseAllOf model = new UpdateExportSettingsResponseAllOf();

    /**
     * Model tests for UpdateExportSettingsResponseAllOf
     */
    @Test
    public void testUpdateExportSettingsResponseAllOf() {
        // TODO: test UpdateExportSettingsResponseAllOf
    }

    /**
     * Test the property 'tenantID'
     */
    @Test
    public void tenantIDTest() {
        // TODO: test tenantID
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
