/*
 * Kibo Catalog Admin Services
 * OpenAPI Spec for Kibo Catalog Admin Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogadministration.api;

import com.kibocommerce.sdk.common.ApiException;
import com.kibocommerce.sdk.catalogadministration.models.CatalogAdminsPriceList;
import com.kibocommerce.sdk.catalogadministration.models.PriceListCollection;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PriceListsApi
 */
@Disabled
public class PriceListsApiTest {

    private final PriceListsApi api = new PriceListsApi();

    /**
     * Add price list
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addPriceListTest() throws ApiException {
        CatalogAdminsPriceList catalogAdminsPriceList = null;
        CatalogAdminsPriceList response = api.addPriceList(catalogAdminsPriceList);
        // TODO: test validations
    }

    /**
     * Delete price list
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deletePriceListTest() throws ApiException {
        String priceListCode = null;
        Boolean cascadeDeleteEntries = null;
        api.deletePriceList(priceListCode, cascadeDeleteEntries);
        // TODO: test validations
    }

    /**
     * Get price list
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPriceListTest() throws ApiException {
        String priceListCode = null;
        CatalogAdminsPriceList response = api.getPriceList(priceListCode);
        // TODO: test validations
    }

    /**
     * Get price lists
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPriceListsTest() throws ApiException {
        Integer startIndex = null;
        Integer pageSize = null;
        String sortBy = null;
        String filter = null;
        PriceListCollection response = api.getPriceLists(startIndex, pageSize, sortBy, filter);
        // TODO: test validations
    }

    /**
     * Update price list
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePriceListTest() throws ApiException {
        String priceListCode = null;
        CatalogAdminsPriceList catalogAdminsPriceList = null;
        CatalogAdminsPriceList response = api.updatePriceList(priceListCode, catalogAdminsPriceList);
        // TODO: test validations
    }

}
