/*
 * Kibo Catalog Admin Services
 * OpenAPI Spec for Kibo Catalog Admin Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogadministration.api;

import com.kibocommerce.sdk.common.ApiException;
import com.kibocommerce.sdk.catalogadministration.models.SuggestSettings;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SearchCategorySuggestSettingsApi
 */
@Disabled
public class SearchCategorySuggestSettingsApiTest {

    private final SearchCategorySuggestSettingsApi api = new SearchCategorySuggestSettingsApi();

    /**
     * Delete category suggest settings
     *
     * Deletes the CategorySuggestSettings for a specific SearchSetting by name.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteCategorySuggestSettingsTest() throws ApiException {
        String name = null;
        api.deleteCategorySuggestSettings(name);
        // TODO: test validations
    }

    /**
     * Get category suggest settings
     *
     * Get CategorySuggestSettings for a specific SearchSettings.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCategorySuggestSettingsTest() throws ApiException {
        String name = null;
        SuggestSettings response = api.getCategorySuggestSettings(name);
        // TODO: test validations
    }

    /**
     * Add/Update category suggest settings
     *
     * Adds or Updates (Upsert) the CategorySuggestSettings for a specific SearchSetting.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateCategorySuggestSettingsTest() throws ApiException {
        String name = null;
        SuggestSettings suggestSettings = null;
        SuggestSettings response = api.updateCategorySuggestSettings(name, suggestSettings);
        // TODO: test validations
    }

}
