/*
 * Kibo Catalog Admin Services
 * OpenAPI Spec for Kibo Catalog Admin Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogadministration.api;

import com.kibocommerce.sdk.common.ApiException;
import com.kibocommerce.sdk.catalogadministration.models.ProductSuggestSettings;
import com.kibocommerce.sdk.catalogadministration.models.SuggestSettings;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SearchProductSuggestSettingsApi
 */
@Disabled
public class SearchProductSuggestSettingsApiTest {

    private final SearchProductSuggestSettingsApi api = new SearchProductSuggestSettingsApi();

    /**
     * Delete product suggest settings
     *
     * Deletes the ProductSuggestSettings for a specific SearchSetting by name.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteProductSuggestSettingsTest() throws ApiException {
        String name = null;
        api.deleteProductSuggestSettings(name);
        // TODO: test validations
    }

    /**
     * Get [roduct suggest settings
     *
     * Get ProductSuggestSettings for a specific SearchSettings by name.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProductSuggestSettingsTest() throws ApiException {
        String name = null;
        SuggestSettings response = api.getProductSuggestSettings(name);
        // TODO: test validations
    }

    /**
     * Add/Update product suggest settings
     *
     * Adds or Updates (Upsert) the ProductSuggestSettings for a specific SearchSetting by name.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateProductSuggestSettingsTest() throws ApiException {
        String name = null;
        ProductSuggestSettings productSuggestSettings = null;
        ProductSuggestSettings response = api.updateProductSuggestSettings(name, productSuggestSettings);
        // TODO: test validations
    }

}
