/*
 * Kibo CommerceRuntime Service
 * OpenAPI Spec for Kibo CommerceRuntime Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.commerce.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CarrierServiceGenerateLabelResponse
 */
public class CarrierServiceGenerateLabelResponseTest {
    private final CarrierServiceGenerateLabelResponse model = new CarrierServiceGenerateLabelResponse();

    /**
     * Model tests for CarrierServiceGenerateLabelResponse
     */
    @Test
    public void testCarrierServiceGenerateLabelResponse() {
        // TODO: test CarrierServiceGenerateLabelResponse
    }

    /**
     * Test the property 'imageURL'
     */
    @Test
    public void imageURLTest() {
        // TODO: test imageURL
    }

    /**
     * Test the property 'integratorId'
     */
    @Test
    public void integratorIdTest() {
        // TODO: test integratorId
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'trackingNumber'
     */
    @Test
    public void trackingNumberTest() {
        // TODO: test trackingNumber
    }

}
