/*
 * Kibo CommerceRuntime Service
 * OpenAPI Spec for Kibo CommerceRuntime Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.commerce.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CartSummary
 */
public class CartSummaryTest {
    private final CartSummary model = new CartSummary();

    /**
     * Model tests for CartSummary
     */
    @Test
    public void testCartSummary() {
        // TODO: test CartSummary
    }

    /**
     * Test the property 'itemCount'
     */
    @Test
    public void itemCountTest() {
        // TODO: test itemCount
    }

    /**
     * Test the property 'totalQuantity'
     */
    @Test
    public void totalQuantityTest() {
        // TODO: test totalQuantity
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

    /**
     * Test the property 'isExpired'
     */
    @Test
    public void isExpiredTest() {
        // TODO: test isExpired
    }

    /**
     * Test the property 'hasActiveCart'
     */
    @Test
    public void hasActiveCartTest() {
        // TODO: test hasActiveCart
    }

}
