/*
 * Kibo CommerceRuntime Service
 * OpenAPI Spec for Kibo CommerceRuntime Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.commerce.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CommerceRuntimeProductPrice
 */
public class CommerceRuntimeProductPriceTest {
    private final CommerceRuntimeProductPrice model = new CommerceRuntimeProductPrice();

    /**
     * Model tests for CommerceRuntimeProductPrice
     */
    @Test
    public void testCommerceRuntimeProductPrice() {
        // TODO: test CommerceRuntimeProductPrice
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'salePrice'
     */
    @Test
    public void salePriceTest() {
        // TODO: test salePrice
    }

    /**
     * Test the property 'tenantOverridePrice'
     */
    @Test
    public void tenantOverridePriceTest() {
        // TODO: test tenantOverridePrice
    }

    /**
     * Test the property 'msrp'
     */
    @Test
    public void msrpTest() {
        // TODO: test msrp
    }

    /**
     * Test the property 'creditValue'
     */
    @Test
    public void creditValueTest() {
        // TODO: test creditValue
    }

    /**
     * Test the property 'priceListCode'
     */
    @Test
    public void priceListCodeTest() {
        // TODO: test priceListCode
    }

    /**
     * Test the property 'priceListEntryMode'
     */
    @Test
    public void priceListEntryModeTest() {
        // TODO: test priceListEntryMode
    }

}
