/*
 * Kibo CommerceRuntime Service
 * OpenAPI Spec for Kibo CommerceRuntime Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.commerce.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DigitalWallet
 */
public class DigitalWalletTest {
    private final DigitalWallet model = new DigitalWallet();

    /**
     * Model tests for DigitalWallet
     */
    @Test
    public void testDigitalWallet() {
        // TODO: test DigitalWallet
    }

    /**
     * Test the property 'digitalWalletData'
     */
    @Test
    public void digitalWalletDataTest() {
        // TODO: test digitalWalletData
    }

    /**
     * Test the property 'cartId'
     */
    @Test
    public void cartIdTest() {
        // TODO: test cartId
    }

}
