/*
 * Kibo CommerceRuntime Service
 * OpenAPI Spec for Kibo CommerceRuntime Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.commerce.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FulfillmentAction
 */
public class FulfillmentActionTest {
    private final FulfillmentAction model = new FulfillmentAction();

    /**
     * Model tests for FulfillmentAction
     */
    @Test
    public void testFulfillmentAction() {
        // TODO: test FulfillmentAction
    }

    /**
     * Test the property 'actionName'
     */
    @Test
    public void actionNameTest() {
        // TODO: test actionName
    }

    /**
     * Test the property 'packageIds'
     */
    @Test
    public void packageIdsTest() {
        // TODO: test packageIds
    }

    /**
     * Test the property 'pickupIds'
     */
    @Test
    public void pickupIdsTest() {
        // TODO: test pickupIds
    }

    /**
     * Test the property 'digitalPackageIds'
     */
    @Test
    public void digitalPackageIdsTest() {
        // TODO: test digitalPackageIds
    }

}
