/*
 * Kibo CommerceRuntime Service
 * OpenAPI Spec for Kibo CommerceRuntime Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.commerce.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.commerce.models.CommerceRuntimeFulfillmentField;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OrderReturnableItem
 */
public class OrderReturnableItemTest {
    private final OrderReturnableItem model = new OrderReturnableItem();

    /**
     * Model tests for OrderReturnableItem
     */
    @Test
    public void testOrderReturnableItem() {
        // TODO: test OrderReturnableItem
    }

    /**
     * Test the property 'productCode'
     */
    @Test
    public void productCodeTest() {
        // TODO: test productCode
    }

    /**
     * Test the property 'productName'
     */
    @Test
    public void productNameTest() {
        // TODO: test productName
    }

    /**
     * Test the property 'shipmentNumber'
     */
    @Test
    public void shipmentNumberTest() {
        // TODO: test shipmentNumber
    }

    /**
     * Test the property 'shipmentItemId'
     */
    @Test
    public void shipmentItemIdTest() {
        // TODO: test shipmentItemId
    }

    /**
     * Test the property 'quantityOrdered'
     */
    @Test
    public void quantityOrderedTest() {
        // TODO: test quantityOrdered
    }

    /**
     * Test the property 'quantityFulfilled'
     */
    @Test
    public void quantityFulfilledTest() {
        // TODO: test quantityFulfilled
    }

    /**
     * Test the property 'quantityReturned'
     */
    @Test
    public void quantityReturnedTest() {
        // TODO: test quantityReturned
    }

    /**
     * Test the property 'quantityRejected'
     */
    @Test
    public void quantityRejectedTest() {
        // TODO: test quantityRejected
    }

    /**
     * Test the property 'quantityReturnable'
     */
    @Test
    public void quantityReturnableTest() {
        // TODO: test quantityReturnable
    }

    /**
     * Test the property 'fulfillmentStatus'
     */
    @Test
    public void fulfillmentStatusTest() {
        // TODO: test fulfillmentStatus
    }

    /**
     * Test the property 'orderItemId'
     */
    @Test
    public void orderItemIdTest() {
        // TODO: test orderItemId
    }

    /**
     * Test the property 'orderLineId'
     */
    @Test
    public void orderLineIdTest() {
        // TODO: test orderLineId
    }

    /**
     * Test the property 'orderItemOptionAttributeFQN'
     */
    @Test
    public void orderItemOptionAttributeFQNTest() {
        // TODO: test orderItemOptionAttributeFQN
    }

    /**
     * Test the property 'unitQuantity'
     */
    @Test
    public void unitQuantityTest() {
        // TODO: test unitQuantity
    }

    /**
     * Test the property 'parentProductCode'
     */
    @Test
    public void parentProductCodeTest() {
        // TODO: test parentProductCode
    }

    /**
     * Test the property 'parentProductName'
     */
    @Test
    public void parentProductNameTest() {
        // TODO: test parentProductName
    }

    /**
     * Test the property 'fulfillmentFields'
     */
    @Test
    public void fulfillmentFieldsTest() {
        // TODO: test fulfillmentFields
    }

    /**
     * Test the property 'sku'
     */
    @Test
    public void skuTest() {
        // TODO: test sku
    }

    /**
     * Test the property 'mfgPartNumber'
     */
    @Test
    public void mfgPartNumberTest() {
        // TODO: test mfgPartNumber
    }

}
