/*
 * Kibo CommerceRuntime Service
 * OpenAPI Spec for Kibo CommerceRuntime Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.commerce.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.commerce.models.AdminUserAuditInfo;
import com.kibocommerce.sdk.commerce.models.CapturableShipmentSummary;
import com.kibocommerce.sdk.commerce.models.PaymentActionTarget;
import com.kibocommerce.sdk.commerce.models.PaymentGatewayResponseData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentInteraction
 */
public class PaymentInteractionTest {
    private final PaymentInteraction model = new PaymentInteraction();

    /**
     * Model tests for PaymentInteraction
     */
    @Test
    public void testPaymentInteraction() {
        // TODO: test PaymentInteraction
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'gatewayInteractionId'
     */
    @Test
    public void gatewayInteractionIdTest() {
        // TODO: test gatewayInteractionId
    }

    /**
     * Test the property 'paymentId'
     */
    @Test
    public void paymentIdTest() {
        // TODO: test paymentId
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    public void orderIdTest() {
        // TODO: test orderId
    }

    /**
     * Test the property 'target'
     */
    @Test
    public void targetTest() {
        // TODO: test target
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'interactionType'
     */
    @Test
    public void interactionTypeTest() {
        // TODO: test interactionType
    }

    /**
     * Test the property 'checkNumber'
     */
    @Test
    public void checkNumberTest() {
        // TODO: test checkNumber
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'paymentEntryStatus'
     */
    @Test
    public void paymentEntryStatusTest() {
        // TODO: test paymentEntryStatus
    }

    /**
     * Test the property 'isRecurring'
     */
    @Test
    public void isRecurringTest() {
        // TODO: test isRecurring
    }

    /**
     * Test the property 'isManual'
     */
    @Test
    public void isManualTest() {
        // TODO: test isManual
    }

    /**
     * Test the property 'gatewayTransactionId'
     */
    @Test
    public void gatewayTransactionIdTest() {
        // TODO: test gatewayTransactionId
    }

    /**
     * Test the property 'gatewayAuthCode'
     */
    @Test
    public void gatewayAuthCodeTest() {
        // TODO: test gatewayAuthCode
    }

    /**
     * Test the property 'gatewayAVSCodes'
     */
    @Test
    public void gatewayAVSCodesTest() {
        // TODO: test gatewayAVSCodes
    }

    /**
     * Test the property 'gatewayCVV2Codes'
     */
    @Test
    public void gatewayCVV2CodesTest() {
        // TODO: test gatewayCVV2Codes
    }

    /**
     * Test the property 'gatewayResponseCode'
     */
    @Test
    public void gatewayResponseCodeTest() {
        // TODO: test gatewayResponseCode
    }

    /**
     * Test the property 'gatewayResponseText'
     */
    @Test
    public void gatewayResponseTextTest() {
        // TODO: test gatewayResponseText
    }

    /**
     * Test the property 'gatewayResponseData'
     */
    @Test
    public void gatewayResponseDataTest() {
        // TODO: test gatewayResponseData
    }

    /**
     * Test the property 'paymentTransactionInteractionIdReference'
     */
    @Test
    public void paymentTransactionInteractionIdReferenceTest() {
        // TODO: test paymentTransactionInteractionIdReference
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'note'
     */
    @Test
    public void noteTest() {
        // TODO: test note
    }

    /**
     * Test the property 'interactionDate'
     */
    @Test
    public void interactionDateTest() {
        // TODO: test interactionDate
    }

    /**
     * Test the property 'auditInfo'
     */
    @Test
    public void auditInfoTest() {
        // TODO: test auditInfo
    }

    /**
     * Test the property 'returnId'
     */
    @Test
    public void returnIdTest() {
        // TODO: test returnId
    }

    /**
     * Test the property 'refundId'
     */
    @Test
    public void refundIdTest() {
        // TODO: test refundId
    }

    /**
     * Test the property 'capturableShipmentsSummary'
     */
    @Test
    public void capturableShipmentsSummaryTest() {
        // TODO: test capturableShipmentsSummary
    }

}
