/*
 * Kibo CommerceRuntime Service
 * OpenAPI Spec for Kibo CommerceRuntime Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.commerce.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.commerce.models.CommerceRuntimeAddress;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PricingTaxContext
 */
public class PricingTaxContextTest {
    private final PricingTaxContext model = new PricingTaxContext();

    /**
     * Model tests for PricingTaxContext
     */
    @Test
    public void testPricingTaxContext() {
        // TODO: test PricingTaxContext
    }

    /**
     * Test the property 'taxContextId'
     */
    @Test
    public void taxContextIdTest() {
        // TODO: test taxContextId
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'taxExemptId'
     */
    @Test
    public void taxExemptIdTest() {
        // TODO: test taxExemptId
    }

    /**
     * Test the property 'originAddress'
     */
    @Test
    public void originAddressTest() {
        // TODO: test originAddress
    }

    /**
     * Test the property 'destinationAddress'
     */
    @Test
    public void destinationAddressTest() {
        // TODO: test destinationAddress
    }

}
