/*
 * Kibo CommerceRuntime Service
 * OpenAPI Spec for Kibo CommerceRuntime Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.commerce.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.commerce.models.PricingDiscount;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PricingAppliedOrderShippingDiscount
 */
public class PricingAppliedOrderShippingDiscountTest {
    private final PricingAppliedOrderShippingDiscount model = new PricingAppliedOrderShippingDiscount();

    /**
     * Model tests for PricingAppliedOrderShippingDiscount
     */
    @Test
    public void testPricingAppliedOrderShippingDiscount() {
        // TODO: test PricingAppliedOrderShippingDiscount
    }

    /**
     * Test the property 'impact'
     */
    @Test
    public void impactTest() {
        // TODO: test impact
    }

    /**
     * Test the property 'discount'
     */
    @Test
    public void discountTest() {
        // TODO: test discount
    }

    /**
     * Test the property 'couponCode'
     */
    @Test
    public void couponCodeTest() {
        // TODO: test couponCode
    }

    /**
     * Test the property 'couponSetId'
     */
    @Test
    public void couponSetIdTest() {
        // TODO: test couponSetId
    }

}
