/*
 * Kibo Fulfillment Service
 * OpenAPI Spec for Kibo Fulfillment Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.fulfillment.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.fulfillment.models.FulfillmentAddress;
import com.kibocommerce.sdk.fulfillment.models.FulfillmentPhone;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FulfillmentContact
 */
public class FulfillmentContactTest {
    private final FulfillmentContact model = new FulfillmentContact();

    /**
     * Model tests for FulfillmentContact
     */
    @Test
    public void testFulfillmentContact() {
        // TODO: test FulfillmentContact
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'companyOrOrganization'
     */
    @Test
    public void companyOrOrganizationTest() {
        // TODO: test companyOrOrganization
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    public void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'lastNameOrSurname'
     */
    @Test
    public void lastNameOrSurnameTest() {
        // TODO: test lastNameOrSurname
    }

    /**
     * Test the property 'middleNameOrInitial'
     */
    @Test
    public void middleNameOrInitialTest() {
        // TODO: test middleNameOrInitial
    }

    /**
     * Test the property 'phoneNumbers'
     */
    @Test
    public void phoneNumbersTest() {
        // TODO: test phoneNumbers
    }

    /**
     * Test the property 'shortFullName'
     */
    @Test
    public void shortFullNameTest() {
        // TODO: test shortFullName
    }

}
