/*
 * Kibo Fulfillment Service
 * OpenAPI Spec for Kibo Fulfillment Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.fulfillment.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FulfillmentAuditInfo
 */
public class FulfillmentAuditInfoTest {
    private final FulfillmentAuditInfo model = new FulfillmentAuditInfo();

    /**
     * Model tests for FulfillmentAuditInfo
     */
    @Test
    public void testFulfillmentAuditInfo() {
        // TODO: test FulfillmentAuditInfo
    }

    /**
     * Test the property 'createBy'
     */
    @Test
    public void createByTest() {
        // TODO: test createBy
    }

    /**
     * Test the property 'createDate'
     */
    @Test
    public void createDateTest() {
        // TODO: test createDate
    }

    /**
     * Test the property 'updateBy'
     */
    @Test
    public void updateByTest() {
        // TODO: test updateBy
    }

    /**
     * Test the property 'updateDate'
     */
    @Test
    public void updateDateTest() {
        // TODO: test updateDate
    }

}
