/*
 * Kibo Fulfillment Service
 * OpenAPI Spec for Kibo Fulfillment Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.fulfillment.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.fulfillment.models.EntityModelOfWorkflowProcess;
import com.kibocommerce.sdk.fulfillment.models.Links;
import com.kibocommerce.sdk.fulfillment.models.PageMetadata;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PagedModelOfEntityModelOfWorkflowProcess
 */
public class PagedModelOfEntityModelOfWorkflowProcessTest {
    private final PagedModelOfEntityModelOfWorkflowProcess model = new PagedModelOfEntityModelOfWorkflowProcess();

    /**
     * Model tests for PagedModelOfEntityModelOfWorkflowProcess
     */
    @Test
    public void testPagedModelOfEntityModelOfWorkflowProcess() {
        // TODO: test PagedModelOfEntityModelOfWorkflowProcess
    }

    /**
     * Test the property 'embedded'
     */
    @Test
    public void embeddedTest() {
        // TODO: test embedded
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

    /**
     * Test the property 'page'
     */
    @Test
    public void pageTest() {
        // TODO: test page
    }

}
