/*
 * Kibo Shipping Admin Service
 * OpenAPI Spec for Kibo Shipping Admin Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.shippingadmin.models;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ShippingAdminHttpVersionPolicy
 */
public class ShippingAdminHttpVersionPolicyTest {
    /**
     * Model tests for ShippingAdminHttpVersionPolicy
     */
    @Test
    public void testShippingAdminHttpVersionPolicy() {
        // TODO: test ShippingAdminHttpVersionPolicy
    }

}
