/*
 * Kibo Shipping Admin Service
 * OpenAPI Spec for Kibo Shipping Admin Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.shippingadmin.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.shippingadmin.models.AppDevHttpContent;
import com.kibocommerce.sdk.shippingadmin.models.ShippingAdminHttpRequestMessage;
import com.kibocommerce.sdk.shippingadmin.models.ShippingAdminHttpStatusCode;
import com.kibocommerce.sdk.shippingadmin.models.StringStringIEnumerableKeyValuePair;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ShippingAdminHttpResponseMessage
 */
public class ShippingAdminHttpResponseMessageTest {
    private final ShippingAdminHttpResponseMessage model = new ShippingAdminHttpResponseMessage();

    /**
     * Model tests for ShippingAdminHttpResponseMessage
     */
    @Test
    public void testShippingAdminHttpResponseMessage() {
        // TODO: test ShippingAdminHttpResponseMessage
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'statusCode'
     */
    @Test
    public void statusCodeTest() {
        // TODO: test statusCode
    }

    /**
     * Test the property 'reasonPhrase'
     */
    @Test
    public void reasonPhraseTest() {
        // TODO: test reasonPhrase
    }

    /**
     * Test the property 'headers'
     */
    @Test
    public void headersTest() {
        // TODO: test headers
    }

    /**
     * Test the property 'trailingHeaders'
     */
    @Test
    public void trailingHeadersTest() {
        // TODO: test trailingHeaders
    }

    /**
     * Test the property 'requestMessage'
     */
    @Test
    public void requestMessageTest() {
        // TODO: test requestMessage
    }

    /**
     * Test the property 'isSuccessStatusCode'
     */
    @Test
    public void isSuccessStatusCodeTest() {
        // TODO: test isSuccessStatusCode
    }

}
