/*
 * Kibo SiteSettings Service
 * OpenAPI Spec for Kibo SiteSettings Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.settings.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.settings.models.AdminUserAuditInfo;
import com.kibocommerce.sdk.settings.models.InventoryExportJob;
import com.kibocommerce.sdk.settings.models.LocationFulfillmentTypeSetting;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InventorySettings
 */
public class InventorySettingsTest {
    private final InventorySettings model = new InventorySettings();

    /**
     * Model tests for InventorySettings
     */
    @Test
    public void testInventorySettings() {
        // TODO: test InventorySettings
    }

    /**
     * Test the property 'inventoryExportJob'
     */
    @Test
    public void inventoryExportJobTest() {
        // TODO: test inventoryExportJob
    }

    /**
     * Test the property 'reserveCartInventoryInterval'
     */
    @Test
    public void reserveCartInventoryIntervalTest() {
        // TODO: test reserveCartInventoryInterval
    }

    /**
     * Test the property 'locationFulfillmentTypeSettings'
     */
    @Test
    public void locationFulfillmentTypeSettingsTest() {
        // TODO: test locationFulfillmentTypeSettings
    }

    /**
     * Test the property 'auditInfo'
     */
    @Test
    public void auditInfoTest() {
        // TODO: test auditInfo
    }

}
