/*
 * Kibo SiteSettings Service
 * OpenAPI Spec for Kibo SiteSettings Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.settings.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.settings.models.PreAuthorizeTransactionTypeDataContract;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PreAuthorizeDefinition
 */
public class PreAuthorizeDefinitionTest {
    private final PreAuthorizeDefinition model = new PreAuthorizeDefinition();

    /**
     * Model tests for PreAuthorizeDefinition
     */
    @Test
    public void testPreAuthorizeDefinition() {
        // TODO: test PreAuthorizeDefinition
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'preAuthorizeTestUrl'
     */
    @Test
    public void preAuthorizeTestUrlTest() {
        // TODO: test preAuthorizeTestUrl
    }

    /**
     * Test the property 'preAuthorizeProdUrl'
     */
    @Test
    public void preAuthorizeProdUrlTest() {
        // TODO: test preAuthorizeProdUrl
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
