/*
 * Kibo SiteSettings Service
 * OpenAPI Spec for Kibo SiteSettings Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.settings.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Route
 */
public class RouteTest {
    private final Route model = new Route();

    /**
     * Model tests for Route
     */
    @Test
    public void testRoute() {
        // TODO: test Route
    }

    /**
     * Test the property 'template'
     */
    @Test
    public void templateTest() {
        // TODO: test template
    }

    /**
     * Test the property 'defaults'
     */
    @Test
    public void defaultsTest() {
        // TODO: test defaults
    }

    /**
     * Test the property 'internalRoute'
     */
    @Test
    public void internalRouteTest() {
        // TODO: test internalRoute
    }

    /**
     * Test the property 'functionId'
     */
    @Test
    public void functionIdTest() {
        // TODO: test functionId
    }

    /**
     * Test the property 'mappings'
     */
    @Test
    public void mappingsTest() {
        // TODO: test mappings
    }

    /**
     * Test the property 'canonical'
     */
    @Test
    public void canonicalTest() {
        // TODO: test canonical
    }

    /**
     * Test the property 'validators'
     */
    @Test
    public void validatorsTest() {
        // TODO: test validators
    }

    /**
     * Test the property 'urlScheme'
     */
    @Test
    public void urlSchemeTest() {
        // TODO: test urlScheme
    }

}
