/*
 * Kibo Location Admin Service
 * OpenAPI Spec for Kibo Location Admin Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.locationadmin.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.locationadmin.models.AdminUserAuditInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LocationLocationGroup
 */
public class LocationLocationGroupTest {
    private final LocationLocationGroup model = new LocationLocationGroup();

    /**
     * Model tests for LocationLocationGroup
     */
    @Test
    public void testLocationLocationGroup() {
        // TODO: test LocationLocationGroup
    }

    /**
     * Test the property 'locationGroupId'
     */
    @Test
    public void locationGroupIdTest() {
        // TODO: test locationGroupId
    }

    /**
     * Test the property 'locationGroupCode'
     */
    @Test
    public void locationGroupCodeTest() {
        // TODO: test locationGroupCode
    }

    /**
     * Test the property 'siteIds'
     */
    @Test
    public void siteIdsTest() {
        // TODO: test siteIds
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'locationCodes'
     */
    @Test
    public void locationCodesTest() {
        // TODO: test locationCodes
    }

    /**
     * Test the property 'auditInfo'
     */
    @Test
    public void auditInfoTest() {
        // TODO: test auditInfo
    }

}
