/*
 * Kibo Reservation Web API
 * OpenAPI Spec for Kibo Reservation Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.reservation.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.reservation.models.Allocati;
import com.kibocommerce.sdk.reservation.models.InventoryTags;
import com.kibocommerce.sdk.reservation.models.Produ;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ReservationItem
 */
public class ReservationItemTest {
    private final ReservationItem model = new ReservationItem();

    /**
     * Model tests for ReservationItem
     */
    @Test
    public void testReservationItem() {
        // TODO: test ReservationItem
    }

    /**
     * Test the property 'lineId'
     */
    @Test
    public void lineIdTest() {
        // TODO: test lineId
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'orderItemId'
     */
    @Test
    public void orderItemIdTest() {
        // TODO: test orderItemId
    }

    /**
     * Test the property 'product'
     */
    @Test
    public void productTest() {
        // TODO: test product
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'fulfillmentLocationCode'
     */
    @Test
    public void fulfillmentLocationCodeTest() {
        // TODO: test fulfillmentLocationCode
    }

    /**
     * Test the property 'fulfillmentMethod'
     */
    @Test
    public void fulfillmentMethodTest() {
        // TODO: test fulfillmentMethod
    }

    /**
     * Test the property 'allocations'
     */
    @Test
    public void allocationsTest() {
        // TODO: test allocations
    }

    /**
     * Test the property 'allowsBackOrder'
     */
    @Test
    public void allowsBackOrderTest() {
        // TODO: test allowsBackOrder
    }

    /**
     * Test the property 'allocationStatus'
     */
    @Test
    public void allocationStatusTest() {
        // TODO: test allocationStatus
    }

    /**
     * Test the property 'inventoryTags'
     */
    @Test
    public void inventoryTagsTest() {
        // TODO: test inventoryTags
    }

}
