/*
 * Kibo SiteSettings Service
 * OpenAPI Spec for Kibo SiteSettings Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.settings.api;

import com.kibocommerce.sdk.common.ApiException;
import com.kibocommerce.sdk.settings.models.SiteShippingHandlingFee;
import com.kibocommerce.sdk.settings.models.SiteShippingSettings;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ShippingSettingsApi
 */
@Disabled
public class ShippingSettingsApiTest {

    private final ShippingSettingsApi api = new ShippingSettingsApi();

    /**
     * Creates the site&#39;s order handling fee as it appears in shipping settings. Allows you to add the return address in shipping settings without modifying any other settings.
     *
     * OBSOLETE: Handling fees are now defined via shipping admin   Creates site&#39;s shipping handling fee.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createOrderHandlingFeeTest() throws ApiException {
        SiteShippingHandlingFee siteShippingHandlingFee = null;
        SiteShippingHandlingFee response = api.createOrderHandlingFee(siteShippingHandlingFee);
        // TODO: test validations
    }

    /**
     * Get Order Handling Fee
     *
     * OBSOLETE: Handling fees are now defined via shipping admin   Retrieves the site&#39;s shipping handling fee.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getOrderHandlingFeeTest() throws ApiException {
        SiteShippingHandlingFee response = api.getOrderHandlingFee();
        // TODO: test validations
    }

    /**
     * Get Site Shipping Settings
     *
     * Retrievs site&#39;s current shipping settings including information about the active shipping rate provider,  return address, shipping methods, and which countries that you can ship to.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSiteShippingSettingsTest() throws ApiException {
        SiteShippingSettings response = api.getSiteShippingSettings();
        // TODO: test validations
    }

    /**
     * Updates the site&#39;s shipping return address as it appears in shipping settings. Allows you to update the address in shipping settings without modifying any other settings.
     *
     * OBSOLETE: Handling fees are now defined via shipping admin   Updates the site&#39;s shipping handling fee.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateOrderHandlingFeeTest() throws ApiException {
        SiteShippingHandlingFee siteShippingHandlingFee = null;
        SiteShippingHandlingFee response = api.updateOrderHandlingFee(siteShippingHandlingFee);
        // TODO: test validations
    }

}
