/*
 * Kibo Customer Service
 * OpenAPI Spec for Kibo Customer Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.customer.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.customer.models.CurrencyAmount;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CommerceSummary
 */
public class CommerceSummaryTest {
    private final CommerceSummary model = new CommerceSummary();

    /**
     * Model tests for CommerceSummary
     */
    @Test
    public void testCommerceSummary() {
        // TODO: test CommerceSummary
    }

    /**
     * Test the property 'totalOrderAmount'
     */
    @Test
    public void totalOrderAmountTest() {
        // TODO: test totalOrderAmount
    }

    /**
     * Test the property 'orderCount'
     */
    @Test
    public void orderCountTest() {
        // TODO: test orderCount
    }

    /**
     * Test the property 'lastOrderDate'
     */
    @Test
    public void lastOrderDateTest() {
        // TODO: test lastOrderDate
    }

    /**
     * Test the property 'wishlistCount'
     */
    @Test
    public void wishlistCountTest() {
        // TODO: test wishlistCount
    }

    /**
     * Test the property 'visitsCount'
     */
    @Test
    public void visitsCountTest() {
        // TODO: test visitsCount
    }

}
