/*
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.inventory.api;

import com.kibocommerce.sdk.common.ApiException;
import com.kibocommerce.sdk.inventory.models.BaseResponse;
import com.kibocommerce.sdk.inventory.models.DeletedCountResponse;
import com.kibocommerce.sdk.inventory.models.TagCategory;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InventoryTagCategoryApi
 */
@Disabled
public class InventoryTagCategoryApiTest {

    private final InventoryTagCategoryApi api = new InventoryTagCategoryApi();

    /**
     * Delete Tag Category
     *
     * Delete a Tag category
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteTagCategoryTest() throws ApiException {
        Integer xVolTenant = null;
        String tagCategoryName = null;
        DeletedCountResponse response = api.deleteTagCategory(xVolTenant, tagCategoryName);
        // TODO: test validations
    }

    /**
     * Get Tag Category
     *
     * Get a tag category
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTagCategoryTest() throws ApiException {
        Integer xVolTenant = null;
        String tagCategoryName = null;
        TagCategory response = api.getTagCategory(xVolTenant, tagCategoryName);
        // TODO: test validations
    }

    /**
     * Get Tag Category All
     *
     * Get all tag categories for a tenant
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTagCategoryAllTest() throws ApiException {
        Integer xVolTenant = null;
        List<TagCategory> response = api.getTagCategoryAll(xVolTenant);
        // TODO: test validations
    }

    /**
     * Update Tag Category
     *
     * Update the designated tag category
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateTagCategoryTest() throws ApiException {
        Integer xVolTenant = null;
        String tagCategoryName = null;
        TagCategory tagCategory = null;
        TagCategory response = api.updateTagCategory(xVolTenant, tagCategoryName, tagCategory);
        // TODO: test validations
    }

}
