/*
 * Kibo ProductRuntime Service
 * OpenAPI Spec for Kibo ProductRuntime Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.solrschemamanager.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SpellingSchemaDefinitionField
 */
public class SpellingSchemaDefinitionFieldTest {
    private final SpellingSchemaDefinitionField model = new SpellingSchemaDefinitionField();

    /**
     * Model tests for SpellingSchemaDefinitionField
     */
    @Test
    public void testSpellingSchemaDefinitionField() {
        // TODO: test SpellingSchemaDefinitionField
    }

    /**
     * Test the property 'ingestFieldName'
     */
    @Test
    public void ingestFieldNameTest() {
        // TODO: test ingestFieldName
    }

}
