/*
 * Kibo Catalog Runtime Services
 * OpenAPI Spec for Kibo Catalog Runtime Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogstorefront.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.catalogstorefront.models.CatalogAdminsAttributeValidation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AttributeDetail
 */
public class AttributeDetailTest {
    private final AttributeDetail model = new AttributeDetail();

    /**
     * Model tests for AttributeDetail
     */
    @Test
    public void testAttributeDetail() {
        // TODO: test AttributeDetail
    }

    /**
     * Test the property 'valueType'
     */
    @Test
    public void valueTypeTest() {
        // TODO: test valueType
    }

    /**
     * Test the property 'inputType'
     */
    @Test
    public void inputTypeTest() {
        // TODO: test inputType
    }

    /**
     * Test the property 'dataType'
     */
    @Test
    public void dataTypeTest() {
        // TODO: test dataType
    }

    /**
     * Test the property 'usageType'
     */
    @Test
    public void usageTypeTest() {
        // TODO: test usageType
    }

    /**
     * Test the property 'dataTypeSequence'
     */
    @Test
    public void dataTypeSequenceTest() {
        // TODO: test dataTypeSequence
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'validation'
     */
    @Test
    public void validationTest() {
        // TODO: test validation
    }

    /**
     * Test the property 'searchableInStorefront'
     */
    @Test
    public void searchableInStorefrontTest() {
        // TODO: test searchableInStorefront
    }

    /**
     * Test the property 'searchDisplayValue'
     */
    @Test
    public void searchDisplayValueTest() {
        // TODO: test searchDisplayValue
    }

    /**
     * Test the property 'allowFilteringAndSortingInStorefront'
     */
    @Test
    public void allowFilteringAndSortingInStorefrontTest() {
        // TODO: test allowFilteringAndSortingInStorefront
    }

    /**
     * Test the property 'indexValueWithCase'
     */
    @Test
    public void indexValueWithCaseTest() {
        // TODO: test indexValueWithCase
    }

    /**
     * Test the property 'customWeightInStorefrontSearch'
     */
    @Test
    public void customWeightInStorefrontSearchTest() {
        // TODO: test customWeightInStorefrontSearch
    }

    /**
     * Test the property 'displayIntention'
     */
    @Test
    public void displayIntentionTest() {
        // TODO: test displayIntention
    }

    /**
     * Test the property 'availableForOrderRouting'
     */
    @Test
    public void availableForOrderRoutingTest() {
        // TODO: test availableForOrderRouting
    }

}
