/*
 * Kibo Catalog Runtime Services
 * OpenAPI Spec for Kibo Catalog Runtime Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogstorefront.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.catalogstorefront.models.AdminUserAuditInfo;
import com.kibocommerce.sdk.catalogstorefront.models.CampaignListingSettings;
import com.kibocommerce.sdk.catalogstorefront.models.CampaignProductSuggestSettings;
import com.kibocommerce.sdk.catalogstorefront.models.CampaignSiteSearchSettings;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CampaignResult
 */
public class CampaignResultTest {
    private final CampaignResult model = new CampaignResult();

    /**
     * Model tests for CampaignResult
     */
    @Test
    public void testCampaignResult() {
        // TODO: test CampaignResult
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'siteId'
     */
    @Test
    public void siteIdTest() {
        // TODO: test siteId
    }

    /**
     * Test the property 'campaignName'
     */
    @Test
    public void campaignNameTest() {
        // TODO: test campaignName
    }

    /**
     * Test the property 'campaignId'
     */
    @Test
    public void campaignIdTest() {
        // TODO: test campaignId
    }

    /**
     * Test the property 'json'
     */
    @Test
    public void jsonTest() {
        // TODO: test json
    }

    /**
     * Test the property 'campaignDescription'
     */
    @Test
    public void campaignDescriptionTest() {
        // TODO: test campaignDescription
    }

    /**
     * Test the property 'campaignStartDate'
     */
    @Test
    public void campaignStartDateTest() {
        // TODO: test campaignStartDate
    }

    /**
     * Test the property 'campaignEndDate'
     */
    @Test
    public void campaignEndDateTest() {
        // TODO: test campaignEndDate
    }

    /**
     * Test the property 'statusId'
     */
    @Test
    public void statusIdTest() {
        // TODO: test statusId
    }

    /**
     * Test the property 'siteSearchSettings'
     */
    @Test
    public void siteSearchSettingsTest() {
        // TODO: test siteSearchSettings
    }

    /**
     * Test the property 'productSuggestSettings'
     */
    @Test
    public void productSuggestSettingsTest() {
        // TODO: test productSuggestSettings
    }

    /**
     * Test the property 'listingSettings'
     */
    @Test
    public void listingSettingsTest() {
        // TODO: test listingSettings
    }

    /**
     * Test the property 'auditInfo'
     */
    @Test
    public void auditInfoTest() {
        // TODO: test auditInfo
    }

}
