/*
 * Kibo Catalog Runtime Services
 * OpenAPI Spec for Kibo Catalog Runtime Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogstorefront.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.catalogstorefront.models.AdminUserAuditInfo;
import com.kibocommerce.sdk.catalogstorefront.models.CatalogRuntimesSearchMerchandizingRuleContext;
import com.kibocommerce.sdk.catalogstorefront.models.SearchMerchandizingRuleImpact;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CatalogRuntimesSearchMerchandizingRule
 */
public class CatalogRuntimesSearchMerchandizingRuleTest {
    private final CatalogRuntimesSearchMerchandizingRule model = new CatalogRuntimesSearchMerchandizingRule();

    /**
     * Model tests for CatalogRuntimesSearchMerchandizingRule
     */
    @Test
    public void testCatalogRuntimesSearchMerchandizingRule() {
        // TODO: test CatalogRuntimesSearchMerchandizingRule
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'context'
     */
    @Test
    public void contextTest() {
        // TODO: test context
    }

    /**
     * Test the property 'ruleImpact'
     */
    @Test
    public void ruleImpactTest() {
        // TODO: test ruleImpact
    }

    /**
     * Test the property 'auditInfo'
     */
    @Test
    public void auditInfoTest() {
        // TODO: test auditInfo
    }

    /**
     * Test the property 'isPersonalizationEnabled'
     */
    @Test
    public void isPersonalizationEnabledTest() {
        // TODO: test isPersonalizationEnabled
    }

}
