/*
 * Kibo Catalog Runtime Services
 * OpenAPI Spec for Kibo Catalog Runtime Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogstorefront.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.catalogstorefront.models.CatalogRuntimesAttributeVocabularyValueDisplayInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CatalogRuntimesProductPropertyValue
 */
public class CatalogRuntimesProductPropertyValueTest {
    private final CatalogRuntimesProductPropertyValue model = new CatalogRuntimesProductPropertyValue();

    /**
     * Model tests for CatalogRuntimesProductPropertyValue
     */
    @Test
    public void testCatalogRuntimesProductPropertyValue() {
        // TODO: test CatalogRuntimesProductPropertyValue
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'stringValue'
     */
    @Test
    public void stringValueTest() {
        // TODO: test stringValue
    }

    /**
     * Test the property 'displayInfo'
     */
    @Test
    public void displayInfoTest() {
        // TODO: test displayInfo
    }

}
