/*
 * Kibo Catalog Runtime Services
 * OpenAPI Spec for Kibo Catalog Runtime Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogstorefront.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.catalogstorefront.models.CatalogRuntimesDiscount;
import com.kibocommerce.sdk.catalogstorefront.models.CatalogRuntimesPackageMeasurements;
import com.kibocommerce.sdk.catalogstorefront.models.CatalogRuntimesProductInventoryInfo;
import com.kibocommerce.sdk.catalogstorefront.models.CatalogRuntimesProductOption;
import com.kibocommerce.sdk.catalogstorefront.models.CatalogRuntimesProductPrice;
import com.kibocommerce.sdk.catalogstorefront.models.CatalogRuntimesProductProperty;
import com.kibocommerce.sdk.catalogstorefront.models.ProductImage;
import com.kibocommerce.sdk.catalogstorefront.models.ProductPriceRange;
import com.kibocommerce.sdk.catalogstorefront.models.ProductPurchasableState;
import com.kibocommerce.sdk.catalogstorefront.models.ProductVolumePrice;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ConfiguredProduct
 */
public class ConfiguredProductTest {
    private final ConfiguredProduct model = new ConfiguredProduct();

    /**
     * Model tests for ConfiguredProduct
     */
    @Test
    public void testConfiguredProduct() {
        // TODO: test ConfiguredProduct
    }

    /**
     * Test the property 'productCode'
     */
    @Test
    public void productCodeTest() {
        // TODO: test productCode
    }

    /**
     * Test the property 'purchaseLocation'
     */
    @Test
    public void purchaseLocationTest() {
        // TODO: test purchaseLocation
    }

    /**
     * Test the property 'fulfillmentTypesSupported'
     */
    @Test
    public void fulfillmentTypesSupportedTest() {
        // TODO: test fulfillmentTypesSupported
    }

    /**
     * Test the property 'variationProductCode'
     */
    @Test
    public void variationProductCodeTest() {
        // TODO: test variationProductCode
    }

    /**
     * Test the property 'upc'
     */
    @Test
    public void upcTest() {
        // TODO: test upc
    }

    /**
     * Test the property 'mfgPartNumber'
     */
    @Test
    public void mfgPartNumberTest() {
        // TODO: test mfgPartNumber
    }

    /**
     * Test the property 'purchasableState'
     */
    @Test
    public void purchasableStateTest() {
        // TODO: test purchasableState
    }

    /**
     * Test the property 'priceRange'
     */
    @Test
    public void priceRangeTest() {
        // TODO: test priceRange
    }

    /**
     * Test the property 'volumePriceBands'
     */
    @Test
    public void volumePriceBandsTest() {
        // TODO: test volumePriceBands
    }

    /**
     * Test the property 'volumePriceRange'
     */
    @Test
    public void volumePriceRangeTest() {
        // TODO: test volumePriceRange
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'availableShippingDiscounts'
     */
    @Test
    public void availableShippingDiscountsTest() {
        // TODO: test availableShippingDiscounts
    }

    /**
     * Test the property 'measurements'
     */
    @Test
    public void measurementsTest() {
        // TODO: test measurements
    }

    /**
     * Test the property 'inventoryInfo'
     */
    @Test
    public void inventoryInfoTest() {
        // TODO: test inventoryInfo
    }

    /**
     * Test the property 'options'
     */
    @Test
    public void optionsTest() {
        // TODO: test options
    }

    /**
     * Test the property 'properties'
     */
    @Test
    public void propertiesTest() {
        // TODO: test properties
    }

    /**
     * Test the property 'priceListEntryTypeProperty'
     */
    @Test
    public void priceListEntryTypePropertyTest() {
        // TODO: test priceListEntryTypeProperty
    }

    /**
     * Test the property 'productImages'
     */
    @Test
    public void productImagesTest() {
        // TODO: test productImages
    }

}
