/*
 * Kibo Catalog Runtime Services
 * OpenAPI Spec for Kibo Catalog Runtime Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogstorefront.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FacetValue
 */
public class FacetValueTest {
    private final FacetValue model = new FacetValue();

    /**
     * Model tests for FacetValue
     */
    @Test
    public void testFacetValue() {
        // TODO: test FacetValue
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'isApplied'
     */
    @Test
    public void isAppliedTest() {
        // TODO: test isApplied
    }

    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'filterValue'
     */
    @Test
    public void filterValueTest() {
        // TODO: test filterValue
    }

    /**
     * Test the property 'rangeQueryValueStart'
     */
    @Test
    public void rangeQueryValueStartTest() {
        // TODO: test rangeQueryValueStart
    }

    /**
     * Test the property 'rangeQueryValueEnd'
     */
    @Test
    public void rangeQueryValueEndTest() {
        // TODO: test rangeQueryValueEnd
    }

    /**
     * Test the property 'parentFacetValue'
     */
    @Test
    public void parentFacetValueTest() {
        // TODO: test parentFacetValue
    }

    /**
     * Test the property 'isDisplayed'
     */
    @Test
    public void isDisplayedTest() {
        // TODO: test isDisplayed
    }

    /**
     * Test the property 'childrenFacetValues'
     */
    @Test
    public void childrenFacetValuesTest() {
        // TODO: test childrenFacetValues
    }

}
