/*
 * Kibo Catalog Runtime Services
 * OpenAPI Spec for Kibo Catalog Runtime Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogstorefront.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PriceListNode
 */
public class PriceListNodeTest {
    private final PriceListNode model = new PriceListNode();

    /**
     * Model tests for PriceListNode
     */
    @Test
    public void testPriceListNode() {
        // TODO: test PriceListNode
    }

    /**
     * Test the property 'priceListCode'
     */
    @Test
    public void priceListCodeTest() {
        // TODO: test priceListCode
    }

    /**
     * Test the property 'priceListId'
     */
    @Test
    public void priceListIdTest() {
        // TODO: test priceListId
    }

    /**
     * Test the property 'parentPriceListId'
     */
    @Test
    public void parentPriceListIdTest() {
        // TODO: test parentPriceListId
    }

    /**
     * Test the property 'priceListLevel'
     */
    @Test
    public void priceListLevelTest() {
        // TODO: test priceListLevel
    }

}
