/*
 * Kibo Catalog Runtime Services
 * OpenAPI Spec for Kibo Catalog Runtime Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogstorefront.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.catalogstorefront.models.CatalogRuntimesProductPrice;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProductPriceRange
 */
public class ProductPriceRangeTest {
    private final ProductPriceRange model = new ProductPriceRange();

    /**
     * Model tests for ProductPriceRange
     */
    @Test
    public void testProductPriceRange() {
        // TODO: test ProductPriceRange
    }

    /**
     * Test the property 'lower'
     */
    @Test
    public void lowerTest() {
        // TODO: test lower
    }

    /**
     * Test the property 'upper'
     */
    @Test
    public void upperTest() {
        // TODO: test upper
    }

}
