/*
 * Kibo Catalog Runtime Services
 * OpenAPI Spec for Kibo Catalog Runtime Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogstorefront.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SolrDebugInfo
 */
public class SolrDebugInfoTest {
    private final SolrDebugInfo model = new SolrDebugInfo();

    /**
     * Model tests for SolrDebugInfo
     */
    @Test
    public void testSolrDebugInfo() {
        // TODO: test SolrDebugInfo
    }

    /**
     * Test the property 'searchTuningRuleCode'
     */
    @Test
    public void searchTuningRuleCodeTest() {
        // TODO: test searchTuningRuleCode
    }

    /**
     * Test the property 'boostedProductCodes'
     */
    @Test
    public void boostedProductCodesTest() {
        // TODO: test boostedProductCodes
    }

    /**
     * Test the property 'blockedProductCodes'
     */
    @Test
    public void blockedProductCodesTest() {
        // TODO: test blockedProductCodes
    }

    /**
     * Test the property 'boostQueries'
     */
    @Test
    public void boostQueriesTest() {
        // TODO: test boostQueries
    }

    /**
     * Test the property 'boostFunctions'
     */
    @Test
    public void boostFunctionsTest() {
        // TODO: test boostFunctions
    }

    /**
     * Test the property 'solrUrl'
     */
    @Test
    public void solrUrlTest() {
        // TODO: test solrUrl
    }

}
