/*
 * Kibo Catalog Runtime Services
 * OpenAPI Spec for Kibo Catalog Runtime Services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.catalogstorefront.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VariationOption
 */
public class VariationOptionTest {
    private final VariationOption model = new VariationOption();

    /**
     * Model tests for VariationOption
     */
    @Test
    public void testVariationOption() {
        // TODO: test VariationOption
    }

    /**
     * Test the property 'valueSequence'
     */
    @Test
    public void valueSequenceTest() {
        // TODO: test valueSequence
    }

    /**
     * Test the property 'attributeFQN'
     */
    @Test
    public void attributeFQNTest() {
        // TODO: test attributeFQN
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
