/*
 * Kibo Fulfillment Service
 * OpenAPI Spec for Kibo Fulfillment Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.fulfillment.api;

import com.kibocommerce.sdk.common.ApiException;
import com.kibocommerce.sdk.fulfillment.models.CollectionModelOfEntityModelOfCustomerSurvey;
import com.kibocommerce.sdk.fulfillment.models.CustomerSurvey;
import com.kibocommerce.sdk.fulfillment.models.EntityModelOfCustomerSurvey;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CustomerSurveyApi
 */
@Disabled
public class CustomerSurveyApiTest {

    private final CustomerSurveyApi api = new CustomerSurveyApi();

    /**
     * Create Survey
     *
     * Create Survey
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createSurveyUsingPOSTTest() throws ApiException {
        Integer shipmentNumber = null;
        CustomerSurvey customerSurvey = null;
        EntityModelOfCustomerSurvey response = api.createSurveyUsingPOST(shipmentNumber, customerSurvey);
        // TODO: test validations
    }

    /**
     * Get Survey
     *
     * Get Survey
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSurveyUsingGETTest() throws ApiException {
        String id = null;
        EntityModelOfCustomerSurvey response = api.getSurveyUsingGET(id);
        // TODO: test validations
    }

    /**
     * Get Surveys
     *
     * Get Surveys
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSurveysUsingGETTest() throws ApiException {
        Integer shipmentNumber = null;
        CollectionModelOfEntityModelOfCustomerSurvey response = api.getSurveysUsingGET(shipmentNumber);
        // TODO: test validations
    }

}
