/*
 * Kibo Location Admin Service
 * OpenAPI Spec for Kibo Location Admin Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.locationadmin.api;

import com.kibocommerce.sdk.common.ApiException;
import com.kibocommerce.sdk.locationadmin.models.LocationGroupConfiguration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LocationGroupConfigurationApi
 */
@Disabled
public class LocationGroupConfigurationApiTest {

    private final LocationGroupConfigurationApi api = new LocationGroupConfigurationApi();

    /**
     * Get Location Group Configuration
     *
     * Get this tenants Location Group Configuration Values by locationGroupCode.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLocationGroupConfigurationTest() throws ApiException {
        String locationGroupCode = null;
        LocationGroupConfiguration response = api.getLocationGroupConfiguration(locationGroupCode);
        // TODO: test validations
    }

    /**
     * Get Location Group Configuration By Location Code
     *
     * Get this tenants Location Group Configuration Values.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLocationGroupConfigurationByLocationCodeTest() throws ApiException {
        String locationCode = null;
        LocationGroupConfiguration response = api.getLocationGroupConfigurationByLocationCode(locationCode);
        // TODO: test validations
    }

    /**
     * Set Location Group Configuration
     *
     * Set this tenants Location Group Configuration Values.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setLocationGroupConfigurationTest() throws ApiException {
        String locationGroupCode = null;
        LocationGroupConfiguration locationGroupConfiguration = null;
        LocationGroupConfiguration response = api.setLocationGroupConfiguration(locationGroupCode, locationGroupConfiguration);
        // TODO: test validations
    }

}
