/*
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.orderrouting.api;

import com.kibocommerce.sdk.common.ApiException;
import com.kibocommerce.sdk.orderrouting.models.ApiDocumentationLocationGroup;
import com.kibocommerce.sdk.orderrouting.models.LocationGroupModel;
import com.kibocommerce.sdk.orderrouting.models.LocationSort;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrderRoutingGroupApi
 */
@Disabled
public class OrderRoutingGroupApiTest {

    private final OrderRoutingGroupApi api = new OrderRoutingGroupApi();

    /**
     * deleteGroup
     *
     * deleteGroup
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteGroupUsingDELETETest() throws ApiException {
        Integer groupID = null;
        Integer xVolSite = null;
        Integer xVolTenant = null;
        api.deleteGroupUsingDELETE(groupID, xVolSite, xVolTenant);
        // TODO: test validations
    }

    /**
     * getGroup
     *
     * getGroup
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getGroupUsingGETTest() throws ApiException {
        Integer groupID = null;
        Integer xVolSite = null;
        Integer xVolTenant = null;
        ApiDocumentationLocationGroup response = api.getGroupUsingGET(groupID, xVolSite, xVolTenant);
        // TODO: test validations
    }

    /**
     * saveGroup
     *
     * saveGroup
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void saveGroupUsingPOSTTest() throws ApiException {
        Integer xVolSite = null;
        Integer xVolTenant = null;
        LocationGroupModel loc = null;
        ApiDocumentationLocationGroup response = api.saveGroupUsingPOST(xVolSite, xVolTenant, loc);
        // TODO: test validations
    }

    /**
     * setGroupFilters
     *
     * setGroupFilters
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setGroupFiltersUsingPOSTTest() throws ApiException {
        Integer groupID = null;
        Integer xVolSite = null;
        Integer xVolTenant = null;
        List<Integer> filterIDs = null;
        ApiDocumentationLocationGroup response = api.setGroupFiltersUsingPOST(groupID, xVolSite, xVolTenant, filterIDs);
        // TODO: test validations
    }

    /**
     * setGroupSorts
     *
     * setGroupSorts
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setGroupSortsUsingPOSTTest() throws ApiException {
        Integer groupID = null;
        Integer xVolSite = null;
        Integer xVolTenant = null;
        List<LocationSort> sorts = null;
        ApiDocumentationLocationGroup response = api.setGroupSortsUsingPOST(groupID, xVolSite, xVolTenant, sorts);
        // TODO: test validations
    }

    /**
     * testGroup
     *
     * testGroup
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void testGroupUsingGETTest() throws ApiException {
        Integer xVolSite = null;
        Integer xVolTenant = null;
        ApiDocumentationLocationGroup response = api.testGroupUsingGET(xVolSite, xVolTenant);
        // TODO: test validations
    }

}
