/*
 * Kibo Admin User Service
 * OpenAPI Spec for Kibo Admin User Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kibocommerce.sdk.adminuser.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kibocommerce.sdk.adminuser.models.DeveloperAccount;
import com.kibocommerce.sdk.adminuser.models.UserProfile;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DeveloperAdminUserAuthTicket
 */
public class DeveloperAdminUserAuthTicketTest {
    private final DeveloperAdminUserAuthTicket model = new DeveloperAdminUserAuthTicket();

    /**
     * Model tests for DeveloperAdminUserAuthTicket
     */
    @Test
    public void testDeveloperAdminUserAuthTicket() {
        // TODO: test DeveloperAdminUserAuthTicket
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'createdOn'
     */
    @Test
    public void createdOnTest() {
        // TODO: test createdOn
    }

    /**
     * Test the property 'jwtAccessToken'
     */
    @Test
    public void jwtAccessTokenTest() {
        // TODO: test jwtAccessToken
    }

    /**
     * Test the property 'accessToken'
     */
    @Test
    public void accessTokenTest() {
        // TODO: test accessToken
    }

    /**
     * Test the property 'accessTokenExpiration'
     */
    @Test
    public void accessTokenExpirationTest() {
        // TODO: test accessTokenExpiration
    }

    /**
     * Test the property 'refreshToken'
     */
    @Test
    public void refreshTokenTest() {
        // TODO: test refreshToken
    }

    /**
     * Test the property 'refreshTokenExpiration'
     */
    @Test
    public void refreshTokenExpirationTest() {
        // TODO: test refreshTokenExpiration
    }

    /**
     * Test the property 'account'
     */
    @Test
    public void accountTest() {
        // TODO: test account
    }

    /**
     * Test the property 'availableAccounts'
     */
    @Test
    public void availableAccountsTest() {
        // TODO: test availableAccounts
    }

    /**
     * Test the property 'grantedBehaviors'
     */
    @Test
    public void grantedBehaviorsTest() {
        // TODO: test grantedBehaviors
    }

}
